(* Generated by coq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module auipc.
  Axiom Rv32AuipcChip :
    forall (F : Ty.t),
    (Ty.apply (Ty.path "openvm_rv32im_circuit::auipc::Rv32AuipcChip") [] [ F ]) =
      (Ty.apply
        (Ty.path "openvm_circuit::arch::integration_api::VmChipWrapper")
        []
        [
          F;
          Ty.apply
            (Ty.path "openvm_rv32im_circuit::adapters::rdwrite::Rv32RdWriteAdapterChip")
            []
            [ F ];
          Ty.path "openvm_rv32im_circuit::auipc::core::Rv32AuipcCoreChip"
        ]).
End auipc.
