(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module ffi.
  (*
  Enum c_void
  {
    const_params := [];
    ty_params := [];
    variants :=
      [
        {
          name := "__variant1";
          item := StructTuple [];
        };
        {
          name := "__variant2";
          item := StructTuple [];
        }
      ];
  }
  *)
  
  Axiom IsDiscriminant_c_void___variant1 : M.IsDiscriminant "core::ffi::c_void::__variant1" 0.
  Axiom IsDiscriminant_c_void___variant2 : M.IsDiscriminant "core::ffi::c_void::__variant2" 1.
  
  Module Impl_core_fmt_Debug_for_core_ffi_c_void.
    Definition Self : Ty.t := Ty.path "core::ffi::c_void".
    
    (*
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("c_void").finish()
        }
    *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.apply (Ty.path "&") [] [ Ty.path "core::ffi::c_void" ], self |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.call_closure (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            M.get_associated_function (|
              Ty.path "core::fmt::builders::DebugStruct",
              "finish",
              [],
              []
            |),
            [
              M.borrow (|
                Pointer.Kind.MutRef,
                M.alloc (|
                  Ty.path "core::fmt::builders::DebugStruct",
                  M.call_closure (|
                    Ty.path "core::fmt::builders::DebugStruct",
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "debug_struct",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "c_void" |) |) |)
                    ]
                  |)
                |)
              |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Debug"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Debug_for_core_ffi_c_void.
End ffi.
