(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

(*
fn main() {
    // Integer addition
    println!("1 + 2 = {}", 1u32 + 2);

    // Integer subtraction
    println!("1 - 2 = {}", 1i32 - 2);
    // TODO ^ Try changing `1i32` to `1u32` to see why the type is important

    // Short-circuiting boolean logic
    println!("true AND false is {}", true && false);
    println!("true OR false is {}", true || false);
    println!("NOT true is {}", !true);

    // Bitwise operations
    println!("0011 AND 0101 is {:04b}", 0b0011u32 & 0b0101);
    println!("0011 OR 0101 is {:04b}", 0b0011u32 | 0b0101);
    println!("0011 XOR 0101 is {:04b}", 0b0011u32 ^ 0b0101);
    println!("1 << 5 is {}", 1u32 << 5);
    println!("0x80 >> 2 is 0x{:x}", 0x80u32 >> 2);

    // Use underscores to improve readability!
    println!("One million is written as {}", 1_000_000u32);
}
*)
Definition main (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
  match ε, τ, α with
  | [], [], [] =>
    ltac:(M.monadic
      (M.read (|
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args : Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "u32" ] ] :=
                      Value.Tuple
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.alloc (|
                              Ty.path "u32",
                              M.call_closure (|
                                Ty.path "u32",
                                BinOp.Wrap.add,
                                [ Value.Integer IntegerKind.U32 1; Value.Integer IntegerKind.U32 2 ]
                              |)
                            |)
                          |)
                        ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_display",
                              [],
                              [ Ty.path "u32" ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 13; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.read (| UnsupportedLiteral |) |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args : Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "i32" ] ] :=
                      Value.Tuple
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.alloc (|
                              Ty.path "i32",
                              M.call_closure (|
                                Ty.path "i32",
                                BinOp.Wrap.sub,
                                [ Value.Integer IntegerKind.I32 1; Value.Integer IntegerKind.I32 2 ]
                              |)
                            |)
                          |)
                        ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_display",
                              [],
                              [ Ty.path "i32" ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 13; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.read (| UnsupportedLiteral |) |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args : Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "bool" ] ] :=
                      Value.Tuple
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.alloc (|
                              Ty.path "bool",
                              LogicalOp.and (|
                                Value.Bool true,
                                ltac:(M.monadic (Value.Bool false))
                              |)
                            |)
                          |)
                        ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_display",
                              [],
                              [ Ty.path "bool" ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 23; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.read (| UnsupportedLiteral |) |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args : Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "bool" ] ] :=
                      Value.Tuple
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.alloc (|
                              Ty.path "bool",
                              LogicalOp.or (|
                                Value.Bool true,
                                ltac:(M.monadic (Value.Bool false))
                              |)
                            |)
                          |)
                        ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_display",
                              [],
                              [ Ty.path "bool" ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 22; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.read (| UnsupportedLiteral |) |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args : Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "bool" ] ] :=
                      Value.Tuple
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.alloc (|
                              Ty.path "bool",
                              M.call_closure (| Ty.path "bool", UnOp.not, [ Value.Bool true ] |)
                            |)
                          |)
                        ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_display",
                              [],
                              [ Ty.path "bool" ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 17; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.read (| UnsupportedLiteral |) |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args : Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "u32" ] ] :=
                      Value.Tuple
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.alloc (|
                              Ty.path "u32",
                              M.call_closure (|
                                Ty.path "u32",
                                BinOp.Wrap.bit_and,
                                [ Value.Integer IntegerKind.U32 3; Value.Integer IntegerKind.U32 5 ]
                              |)
                            |)
                          |)
                        ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_binary",
                              [],
                              [ Ty.path "u32" ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 28; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.read (| UnsupportedLiteral |) |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args : Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "u32" ] ] :=
                      Value.Tuple
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.alloc (|
                              Ty.path "u32",
                              M.call_closure (|
                                Ty.path "u32",
                                BinOp.Wrap.bit_or,
                                [ Value.Integer IntegerKind.U32 3; Value.Integer IntegerKind.U32 5 ]
                              |)
                            |)
                          |)
                        ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_binary",
                              [],
                              [ Ty.path "u32" ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 27; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.read (| UnsupportedLiteral |) |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args : Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "u32" ] ] :=
                      Value.Tuple
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.alloc (|
                              Ty.path "u32",
                              M.call_closure (|
                                Ty.path "u32",
                                BinOp.Wrap.bit_xor,
                                [ Value.Integer IntegerKind.U32 3; Value.Integer IntegerKind.U32 5 ]
                              |)
                            |)
                          |)
                        ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_binary",
                              [],
                              [ Ty.path "u32" ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 28; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.read (| UnsupportedLiteral |) |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args : Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "u32" ] ] :=
                      Value.Tuple
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.alloc (|
                              Ty.path "u32",
                              M.call_closure (|
                                Ty.path "u32",
                                BinOp.Wrap.shl,
                                [ Value.Integer IntegerKind.U32 1; Value.Integer IntegerKind.I32 5 ]
                              |)
                            |)
                          |)
                        ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_display",
                              [],
                              [ Ty.path "u32" ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 15; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.read (| UnsupportedLiteral |) |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args : Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "u32" ] ] :=
                      Value.Tuple
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.alloc (|
                              Ty.path "u32",
                              M.call_closure (|
                                Ty.path "u32",
                                BinOp.Wrap.shr,
                                [ Value.Integer IntegerKind.U32 128; Value.Integer IntegerKind.I32 2
                                ]
                              |)
                            |)
                          |)
                        ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_lower_hex",
                              [],
                              [ Ty.path "u32" ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 20; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.read (| UnsupportedLiteral |) |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.call_closure (|
                    Ty.path "core::fmt::Arguments",
                    M.get_associated_function (|
                      Ty.path "core::fmt::Arguments",
                      "from_str_nonconst",
                      [],
                      []
                    |),
                    [ mk_str (| "One million is written as 1000000
" |) ]
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        M.alloc (| Ty.tuple [], Value.Tuple [] |)
      |)))
  | _, _, _ => M.impossible "wrong number of arguments"
  end.

Global Instance Instance_IsFunction_main : M.IsFunction.C "literals_operators::main" main.
Admitted.
Global Typeclasses Opaque main.
