(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module processor.
  Module revoke.
    (*
    pub fn process_revoke(accounts: &[AccountInfo]) -> ProgramResult {
        let [source_account_info, remaining @ ..] = accounts else {
            return Err(ProgramError::NotEnoughAccountKeys);
        };
    
        // SAFETY: single mutable borrow to `source_account_info` account data and
        // `load_mut` validates that the account is initialized.
        let source_account =
            unsafe { load_mut::<Account>(source_account_info.borrow_mut_data_unchecked())? };
    
        // Unpacking the remaining accounts to get the owner account at this point
        // to maintain the same order as SPL Token.
        let [owner_info, remaining @ ..] = remaining else {
            return Err(ProgramError::NotEnoughAccountKeys);
        };
    
        if source_account.is_frozen()? {
            return Err(TokenError::AccountFrozen.into());
        }
    
        // SAFETY: `owner_info` is not currently borrowed.
        unsafe { validate_owner(&source_account.owner, owner_info, remaining)? }
    
        source_account.clear_delegate();
        source_account.set_delegated_amount(0);
    
        Ok(())
    }
    *)
    Definition process_revoke (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ accounts ] =>
        ltac:(M.monadic
          (let accounts :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.apply (Ty.path "slice") [] [ Ty.path "pinocchio::account_info::AccountInfo" ]
                ],
              accounts
            |) in
          M.catch_return
            (Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "pinocchio::program_error::ProgramError" ]) (|
            ltac:(M.monadic
              (M.match_operator (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [ Ty.tuple []; Ty.path "pinocchio::program_error::ProgramError" ],
                accounts,
                [
                  fun γ =>
                    ltac:(M.monadic
                      (let γ := M.deref (| M.read (| γ |) |) in
                      let γ1_0 := M.SubPointer.get_slice_index (| γ, 0 |) in
                      let γ1_rest := M.SubPointer.get_slice_rest (| γ, 1, 0 |) in
                      let source_account_info :=
                        M.alloc (|
                          Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.path "pinocchio::account_info::AccountInfo" ],
                          γ1_0
                        |) in
                      let remaining :=
                        M.alloc (|
                          Ty.apply
                            (Ty.path "&")
                            []
                            [
                              Ty.apply
                                (Ty.path "slice")
                                []
                                [ Ty.path "pinocchio::account_info::AccountInfo" ]
                            ],
                          γ1_rest
                        |) in
                      M.read (|
                        let~ source_account :
                            Ty.apply
                              (Ty.path "&mut")
                              []
                              [ Ty.path "pinocchio_token_interface::state::account::Account" ] :=
                          M.borrow (|
                            Pointer.Kind.MutRef,
                            M.deref (|
                              M.match_operator (|
                                Ty.apply
                                  (Ty.path "&mut")
                                  []
                                  [ Ty.path "pinocchio_token_interface::state::account::Account" ],
                                M.alloc (|
                                  Ty.apply
                                    (Ty.path "core::ops::control_flow::ControlFlow")
                                    []
                                    [
                                      Ty.apply
                                        (Ty.path "core::result::Result")
                                        []
                                        [
                                          Ty.path "core::convert::Infallible";
                                          Ty.path "pinocchio::program_error::ProgramError"
                                        ];
                                      Ty.apply
                                        (Ty.path "&mut")
                                        []
                                        [
                                          Ty.path
                                            "pinocchio_token_interface::state::account::Account"
                                        ]
                                    ],
                                  M.call_closure (|
                                    Ty.apply
                                      (Ty.path "core::ops::control_flow::ControlFlow")
                                      []
                                      [
                                        Ty.apply
                                          (Ty.path "core::result::Result")
                                          []
                                          [
                                            Ty.path "core::convert::Infallible";
                                            Ty.path "pinocchio::program_error::ProgramError"
                                          ];
                                        Ty.apply
                                          (Ty.path "&mut")
                                          []
                                          [
                                            Ty.path
                                              "pinocchio_token_interface::state::account::Account"
                                          ]
                                      ],
                                    M.get_trait_method (|
                                      "core::ops::try_trait::Try",
                                      Ty.apply
                                        (Ty.path "core::result::Result")
                                        []
                                        [
                                          Ty.apply
                                            (Ty.path "&mut")
                                            []
                                            [
                                              Ty.path
                                                "pinocchio_token_interface::state::account::Account"
                                            ];
                                          Ty.path "pinocchio::program_error::ProgramError"
                                        ],
                                      [],
                                      [],
                                      "branch",
                                      [],
                                      []
                                    |),
                                    [
                                      M.call_closure (|
                                        Ty.apply
                                          (Ty.path "core::result::Result")
                                          []
                                          [
                                            Ty.apply
                                              (Ty.path "&mut")
                                              []
                                              [
                                                Ty.path
                                                  "pinocchio_token_interface::state::account::Account"
                                              ];
                                            Ty.path "pinocchio::program_error::ProgramError"
                                          ],
                                        M.get_function (|
                                          "pinocchio_token_interface::state::load_mut",
                                          [],
                                          [
                                            Ty.path
                                              "pinocchio_token_interface::state::account::Account"
                                          ]
                                        |),
                                        [
                                          M.borrow (|
                                            Pointer.Kind.MutRef,
                                            M.deref (|
                                              M.call_closure (|
                                                Ty.apply
                                                  (Ty.path "&mut")
                                                  []
                                                  [ Ty.apply (Ty.path "slice") [] [ Ty.path "u8" ]
                                                  ],
                                                M.get_associated_function (|
                                                  Ty.path "pinocchio::account_info::AccountInfo",
                                                  "borrow_mut_data_unchecked",
                                                  [],
                                                  []
                                                |),
                                                [
                                                  M.borrow (|
                                                    Pointer.Kind.Ref,
                                                    M.deref (| M.read (| source_account_info |) |)
                                                  |)
                                                ]
                                              |)
                                            |)
                                          |)
                                        ]
                                      |)
                                    ]
                                  |)
                                |),
                                [
                                  fun γ =>
                                    ltac:(M.monadic
                                      (let γ0_0 :=
                                        M.SubPointer.get_struct_tuple_field (|
                                          γ,
                                          "core::ops::control_flow::ControlFlow::Break",
                                          0
                                        |) in
                                      let residual :=
                                        M.copy (|
                                          Ty.apply
                                            (Ty.path "core::result::Result")
                                            []
                                            [
                                              Ty.path "core::convert::Infallible";
                                              Ty.path "pinocchio::program_error::ProgramError"
                                            ],
                                          γ0_0
                                        |) in
                                      M.never_to_any (|
                                        M.read (|
                                          M.return_ (|
                                            M.call_closure (|
                                              Ty.apply
                                                (Ty.path "core::result::Result")
                                                []
                                                [
                                                  Ty.tuple [];
                                                  Ty.path "pinocchio::program_error::ProgramError"
                                                ],
                                              M.get_trait_method (|
                                                "core::ops::try_trait::FromResidual",
                                                Ty.apply
                                                  (Ty.path "core::result::Result")
                                                  []
                                                  [
                                                    Ty.tuple [];
                                                    Ty.path "pinocchio::program_error::ProgramError"
                                                  ],
                                                [],
                                                [
                                                  Ty.apply
                                                    (Ty.path "core::result::Result")
                                                    []
                                                    [
                                                      Ty.path "core::convert::Infallible";
                                                      Ty.path
                                                        "pinocchio::program_error::ProgramError"
                                                    ]
                                                ],
                                                "from_residual",
                                                [],
                                                []
                                              |),
                                              [ M.read (| residual |) ]
                                            |)
                                          |)
                                        |)
                                      |)));
                                  fun γ =>
                                    ltac:(M.monadic
                                      (let γ0_0 :=
                                        M.SubPointer.get_struct_tuple_field (|
                                          γ,
                                          "core::ops::control_flow::ControlFlow::Continue",
                                          0
                                        |) in
                                      let val :=
                                        M.copy (|
                                          Ty.apply
                                            (Ty.path "&mut")
                                            []
                                            [
                                              Ty.path
                                                "pinocchio_token_interface::state::account::Account"
                                            ],
                                          γ0_0
                                        |) in
                                      M.read (| val |)))
                                ]
                              |)
                            |)
                          |) in
                        M.alloc (|
                          Ty.apply
                            (Ty.path "core::result::Result")
                            []
                            [ Ty.tuple []; Ty.path "pinocchio::program_error::ProgramError" ],
                          M.match_operator (|
                            Ty.apply
                              (Ty.path "core::result::Result")
                              []
                              [ Ty.tuple []; Ty.path "pinocchio::program_error::ProgramError" ],
                            remaining,
                            [
                              fun γ =>
                                ltac:(M.monadic
                                  (let γ := M.deref (| M.read (| γ |) |) in
                                  let γ1_0 := M.SubPointer.get_slice_index (| γ, 0 |) in
                                  let γ1_rest := M.SubPointer.get_slice_rest (| γ, 1, 0 |) in
                                  let owner_info :=
                                    M.alloc (|
                                      Ty.apply
                                        (Ty.path "&")
                                        []
                                        [ Ty.path "pinocchio::account_info::AccountInfo" ],
                                      γ1_0
                                    |) in
                                  let remaining :=
                                    M.alloc (|
                                      Ty.apply
                                        (Ty.path "&")
                                        []
                                        [
                                          Ty.apply
                                            (Ty.path "slice")
                                            []
                                            [ Ty.path "pinocchio::account_info::AccountInfo" ]
                                        ],
                                      γ1_rest
                                    |) in
                                  M.read (|
                                    let~ _ : Ty.tuple [] :=
                                      M.match_operator (|
                                        Ty.tuple [],
                                        M.alloc (| Ty.tuple [], Value.Tuple [] |),
                                        [
                                          fun γ =>
                                            ltac:(M.monadic
                                              (let γ :=
                                                M.use
                                                  (M.alloc (|
                                                    Ty.path "bool",
                                                    M.match_operator (|
                                                      Ty.path "bool",
                                                      M.alloc (|
                                                        Ty.apply
                                                          (Ty.path
                                                            "core::ops::control_flow::ControlFlow")
                                                          []
                                                          [
                                                            Ty.apply
                                                              (Ty.path "core::result::Result")
                                                              []
                                                              [
                                                                Ty.path "core::convert::Infallible";
                                                                Ty.path
                                                                  "pinocchio::program_error::ProgramError"
                                                              ];
                                                            Ty.path "bool"
                                                          ],
                                                        M.call_closure (|
                                                          Ty.apply
                                                            (Ty.path
                                                              "core::ops::control_flow::ControlFlow")
                                                            []
                                                            [
                                                              Ty.apply
                                                                (Ty.path "core::result::Result")
                                                                []
                                                                [
                                                                  Ty.path
                                                                    "core::convert::Infallible";
                                                                  Ty.path
                                                                    "pinocchio::program_error::ProgramError"
                                                                ];
                                                              Ty.path "bool"
                                                            ],
                                                          M.get_trait_method (|
                                                            "core::ops::try_trait::Try",
                                                            Ty.apply
                                                              (Ty.path "core::result::Result")
                                                              []
                                                              [
                                                                Ty.path "bool";
                                                                Ty.path
                                                                  "pinocchio::program_error::ProgramError"
                                                              ],
                                                            [],
                                                            [],
                                                            "branch",
                                                            [],
                                                            []
                                                          |),
                                                          [
                                                            M.call_closure (|
                                                              Ty.apply
                                                                (Ty.path "core::result::Result")
                                                                []
                                                                [
                                                                  Ty.path "bool";
                                                                  Ty.path
                                                                    "pinocchio::program_error::ProgramError"
                                                                ],
                                                              M.get_associated_function (|
                                                                Ty.path
                                                                  "pinocchio_token_interface::state::account::Account",
                                                                "is_frozen",
                                                                [],
                                                                []
                                                              |),
                                                              [
                                                                M.borrow (|
                                                                  Pointer.Kind.Ref,
                                                                  M.deref (|
                                                                    M.read (| source_account |)
                                                                  |)
                                                                |)
                                                              ]
                                                            |)
                                                          ]
                                                        |)
                                                      |),
                                                      [
                                                        fun γ =>
                                                          ltac:(M.monadic
                                                            (let γ0_0 :=
                                                              M.SubPointer.get_struct_tuple_field (|
                                                                γ,
                                                                "core::ops::control_flow::ControlFlow::Break",
                                                                0
                                                              |) in
                                                            let residual :=
                                                              M.copy (|
                                                                Ty.apply
                                                                  (Ty.path "core::result::Result")
                                                                  []
                                                                  [
                                                                    Ty.path
                                                                      "core::convert::Infallible";
                                                                    Ty.path
                                                                      "pinocchio::program_error::ProgramError"
                                                                  ],
                                                                γ0_0
                                                              |) in
                                                            M.never_to_any (|
                                                              M.read (|
                                                                M.return_ (|
                                                                  M.call_closure (|
                                                                    Ty.apply
                                                                      (Ty.path
                                                                        "core::result::Result")
                                                                      []
                                                                      [
                                                                        Ty.tuple [];
                                                                        Ty.path
                                                                          "pinocchio::program_error::ProgramError"
                                                                      ],
                                                                    M.get_trait_method (|
                                                                      "core::ops::try_trait::FromResidual",
                                                                      Ty.apply
                                                                        (Ty.path
                                                                          "core::result::Result")
                                                                        []
                                                                        [
                                                                          Ty.tuple [];
                                                                          Ty.path
                                                                            "pinocchio::program_error::ProgramError"
                                                                        ],
                                                                      [],
                                                                      [
                                                                        Ty.apply
                                                                          (Ty.path
                                                                            "core::result::Result")
                                                                          []
                                                                          [
                                                                            Ty.path
                                                                              "core::convert::Infallible";
                                                                            Ty.path
                                                                              "pinocchio::program_error::ProgramError"
                                                                          ]
                                                                      ],
                                                                      "from_residual",
                                                                      [],
                                                                      []
                                                                    |),
                                                                    [ M.read (| residual |) ]
                                                                  |)
                                                                |)
                                                              |)
                                                            |)));
                                                        fun γ =>
                                                          ltac:(M.monadic
                                                            (let γ0_0 :=
                                                              M.SubPointer.get_struct_tuple_field (|
                                                                γ,
                                                                "core::ops::control_flow::ControlFlow::Continue",
                                                                0
                                                              |) in
                                                            let val :=
                                                              M.copy (| Ty.path "bool", γ0_0 |) in
                                                            M.read (| val |)))
                                                      ]
                                                    |)
                                                  |)) in
                                              let _ :=
                                                is_constant_or_break_match (|
                                                  M.read (| γ |),
                                                  Value.Bool true
                                                |) in
                                              M.never_to_any (|
                                                M.read (|
                                                  M.return_ (|
                                                    Value.StructTuple
                                                      "core::result::Result::Err"
                                                      []
                                                      [
                                                        Ty.tuple [];
                                                        Ty.path
                                                          "pinocchio::program_error::ProgramError"
                                                      ]
                                                      [
                                                        M.call_closure (|
                                                          Ty.path
                                                            "pinocchio::program_error::ProgramError",
                                                          M.get_trait_method (|
                                                            "core::convert::Into",
                                                            Ty.path
                                                              "pinocchio_token_interface::error::TokenError",
                                                            [],
                                                            [
                                                              Ty.path
                                                                "pinocchio::program_error::ProgramError"
                                                            ],
                                                            "into",
                                                            [],
                                                            []
                                                          |),
                                                          [
                                                            Value.StructTuple
                                                              "pinocchio_token_interface::error::TokenError::AccountFrozen"
                                                              []
                                                              []
                                                              []
                                                          ]
                                                        |)
                                                      ]
                                                  |)
                                                |)
                                              |)));
                                          fun γ => ltac:(M.monadic (Value.Tuple []))
                                        ]
                                      |) in
                                    let~ _ : Ty.tuple [] :=
                                      M.match_operator (|
                                        Ty.tuple [],
                                        M.alloc (|
                                          Ty.apply
                                            (Ty.path "core::ops::control_flow::ControlFlow")
                                            []
                                            [
                                              Ty.apply
                                                (Ty.path "core::result::Result")
                                                []
                                                [
                                                  Ty.path "core::convert::Infallible";
                                                  Ty.path "pinocchio::program_error::ProgramError"
                                                ];
                                              Ty.tuple []
                                            ],
                                          M.call_closure (|
                                            Ty.apply
                                              (Ty.path "core::ops::control_flow::ControlFlow")
                                              []
                                              [
                                                Ty.apply
                                                  (Ty.path "core::result::Result")
                                                  []
                                                  [
                                                    Ty.path "core::convert::Infallible";
                                                    Ty.path "pinocchio::program_error::ProgramError"
                                                  ];
                                                Ty.tuple []
                                              ],
                                            M.get_trait_method (|
                                              "core::ops::try_trait::Try",
                                              Ty.apply
                                                (Ty.path "core::result::Result")
                                                []
                                                [
                                                  Ty.tuple [];
                                                  Ty.path "pinocchio::program_error::ProgramError"
                                                ],
                                              [],
                                              [],
                                              "branch",
                                              [],
                                              []
                                            |),
                                            [
                                              M.call_closure (|
                                                Ty.apply
                                                  (Ty.path "core::result::Result")
                                                  []
                                                  [
                                                    Ty.tuple [];
                                                    Ty.path "pinocchio::program_error::ProgramError"
                                                  ],
                                                M.get_function (|
                                                  "pinocchio_token_program::processor::validate_owner",
                                                  [],
                                                  []
                                                |),
                                                [
                                                  M.borrow (|
                                                    Pointer.Kind.Ref,
                                                    M.deref (|
                                                      M.borrow (|
                                                        Pointer.Kind.Ref,
                                                        M.SubPointer.get_struct_record_field (|
                                                          M.deref (| M.read (| source_account |) |),
                                                          "pinocchio_token_interface::state::account::Account",
                                                          "owner"
                                                        |)
                                                      |)
                                                    |)
                                                  |);
                                                  M.borrow (|
                                                    Pointer.Kind.Ref,
                                                    M.deref (| M.read (| owner_info |) |)
                                                  |);
                                                  M.borrow (|
                                                    Pointer.Kind.Ref,
                                                    M.deref (| M.read (| remaining |) |)
                                                  |)
                                                ]
                                              |)
                                            ]
                                          |)
                                        |),
                                        [
                                          fun γ =>
                                            ltac:(M.monadic
                                              (let γ0_0 :=
                                                M.SubPointer.get_struct_tuple_field (|
                                                  γ,
                                                  "core::ops::control_flow::ControlFlow::Break",
                                                  0
                                                |) in
                                              let residual :=
                                                M.copy (|
                                                  Ty.apply
                                                    (Ty.path "core::result::Result")
                                                    []
                                                    [
                                                      Ty.path "core::convert::Infallible";
                                                      Ty.path
                                                        "pinocchio::program_error::ProgramError"
                                                    ],
                                                  γ0_0
                                                |) in
                                              M.never_to_any (|
                                                M.read (|
                                                  M.return_ (|
                                                    M.call_closure (|
                                                      Ty.apply
                                                        (Ty.path "core::result::Result")
                                                        []
                                                        [
                                                          Ty.tuple [];
                                                          Ty.path
                                                            "pinocchio::program_error::ProgramError"
                                                        ],
                                                      M.get_trait_method (|
                                                        "core::ops::try_trait::FromResidual",
                                                        Ty.apply
                                                          (Ty.path "core::result::Result")
                                                          []
                                                          [
                                                            Ty.tuple [];
                                                            Ty.path
                                                              "pinocchio::program_error::ProgramError"
                                                          ],
                                                        [],
                                                        [
                                                          Ty.apply
                                                            (Ty.path "core::result::Result")
                                                            []
                                                            [
                                                              Ty.path "core::convert::Infallible";
                                                              Ty.path
                                                                "pinocchio::program_error::ProgramError"
                                                            ]
                                                        ],
                                                        "from_residual",
                                                        [],
                                                        []
                                                      |),
                                                      [ M.read (| residual |) ]
                                                    |)
                                                  |)
                                                |)
                                              |)));
                                          fun γ =>
                                            ltac:(M.monadic
                                              (let γ0_0 :=
                                                M.SubPointer.get_struct_tuple_field (|
                                                  γ,
                                                  "core::ops::control_flow::ControlFlow::Continue",
                                                  0
                                                |) in
                                              let val := M.copy (| Ty.tuple [], γ0_0 |) in
                                              M.read (| val |)))
                                        ]
                                      |) in
                                    let~ _ : Ty.tuple [] :=
                                      M.call_closure (|
                                        Ty.tuple [],
                                        M.get_associated_function (|
                                          Ty.path
                                            "pinocchio_token_interface::state::account::Account",
                                          "clear_delegate",
                                          [],
                                          []
                                        |),
                                        [
                                          M.borrow (|
                                            Pointer.Kind.MutRef,
                                            M.deref (| M.read (| source_account |) |)
                                          |)
                                        ]
                                      |) in
                                    let~ _ : Ty.tuple [] :=
                                      M.call_closure (|
                                        Ty.tuple [],
                                        M.get_associated_function (|
                                          Ty.path
                                            "pinocchio_token_interface::state::account::Account",
                                          "set_delegated_amount",
                                          [],
                                          []
                                        |),
                                        [
                                          M.borrow (|
                                            Pointer.Kind.MutRef,
                                            M.deref (| M.read (| source_account |) |)
                                          |);
                                          Value.Integer IntegerKind.U64 0
                                        ]
                                      |) in
                                    M.alloc (|
                                      Ty.apply
                                        (Ty.path "core::result::Result")
                                        []
                                        [
                                          Ty.tuple [];
                                          Ty.path "pinocchio::program_error::ProgramError"
                                        ],
                                      Value.StructTuple
                                        "core::result::Result::Ok"
                                        []
                                        [
                                          Ty.tuple [];
                                          Ty.path "pinocchio::program_error::ProgramError"
                                        ]
                                        [ Value.Tuple [] ]
                                    |)
                                  |)));
                              fun γ =>
                                ltac:(M.monadic
                                  (M.read (|
                                    M.return_ (|
                                      Value.StructTuple
                                        "core::result::Result::Err"
                                        []
                                        [
                                          Ty.tuple [];
                                          Ty.path "pinocchio::program_error::ProgramError"
                                        ]
                                        [
                                          Value.StructTuple
                                            "pinocchio::program_error::ProgramError::NotEnoughAccountKeys"
                                            []
                                            []
                                            []
                                        ]
                                    |)
                                  |)))
                            ]
                          |)
                        |)
                      |)));
                  fun γ =>
                    ltac:(M.monadic
                      (M.read (|
                        M.return_ (|
                          Value.StructTuple
                            "core::result::Result::Err"
                            []
                            [ Ty.tuple []; Ty.path "pinocchio::program_error::ProgramError" ]
                            [
                              Value.StructTuple
                                "pinocchio::program_error::ProgramError::NotEnoughAccountKeys"
                                []
                                []
                                []
                            ]
                        |)
                      |)))
                ]
              |)))
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance Instance_IsFunction_process_revoke :
      M.IsFunction.C "pinocchio_token_program::processor::revoke::process_revoke" process_revoke.
    Admitted.
    Global Typeclasses Opaque process_revoke.
  End revoke.
End processor.
