(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module interpreter_action.
  (*
  Enum FrameInput
  {
    const_params := [];
    ty_params := [];
    variants :=
      [
        {
          name := "Empty";
          item := StructTuple [];
        };
        {
          name := "Call";
          item :=
            StructTuple
              [
                Ty.apply
                  (Ty.path "alloc::boxed::Box")
                  []
                  [
                    Ty.path "revm_interpreter::interpreter_action::call_inputs::CallInputs";
                    Ty.path "alloc::alloc::Global"
                  ]
              ];
        };
        {
          name := "Create";
          item :=
            StructTuple
              [
                Ty.apply
                  (Ty.path "alloc::boxed::Box")
                  []
                  [
                    Ty.path "revm_interpreter::interpreter_action::create_inputs::CreateInputs";
                    Ty.path "alloc::alloc::Global"
                  ]
              ];
        }
      ];
  }
  *)
  
  Axiom IsDiscriminant_FrameInput_Empty :
    M.IsDiscriminant "revm_interpreter::interpreter_action::FrameInput::Empty" 0.
  Axiom IsDiscriminant_FrameInput_Call :
    M.IsDiscriminant "revm_interpreter::interpreter_action::FrameInput::Call" 1.
  Axiom IsDiscriminant_FrameInput_Create :
    M.IsDiscriminant "revm_interpreter::interpreter_action::FrameInput::Create" 2.
  
  Module Impl_core_clone_Clone_for_revm_interpreter_interpreter_action_FrameInput.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::FrameInput".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
              self
            |) in
          M.match_operator (|
            Ty.path "revm_interpreter::interpreter_action::FrameInput",
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let _ :=
                    M.is_struct_tuple (|
                      γ,
                      "revm_interpreter::interpreter_action::FrameInput::Empty"
                    |) in
                  Value.StructTuple
                    "revm_interpreter::interpreter_action::FrameInput::Empty"
                    []
                    []
                    []));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::FrameInput::Call",
                      0
                    |) in
                  let _ := M.read (| γ1_0 |) in
                  let __self_0 :=
                    M.alloc (|
                      Ty.apply
                        (Ty.path "&")
                        []
                        [
                          Ty.apply
                            (Ty.path "alloc::boxed::Box")
                            []
                            [
                              Ty.path
                                "revm_interpreter::interpreter_action::call_inputs::CallInputs";
                              Ty.path "alloc::alloc::Global"
                            ]
                        ],
                      M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                    |) in
                  Value.StructTuple
                    "revm_interpreter::interpreter_action::FrameInput::Call"
                    []
                    []
                    [
                      M.call_closure (|
                        Ty.apply
                          (Ty.path "alloc::boxed::Box")
                          []
                          [
                            Ty.path "revm_interpreter::interpreter_action::call_inputs::CallInputs";
                            Ty.path "alloc::alloc::Global"
                          ],
                        M.get_trait_method (|
                          "core::clone::Clone",
                          Ty.apply
                            (Ty.path "alloc::boxed::Box")
                            []
                            [
                              Ty.path
                                "revm_interpreter::interpreter_action::call_inputs::CallInputs";
                              Ty.path "alloc::alloc::Global"
                            ],
                          [],
                          [],
                          "clone",
                          [],
                          []
                        |),
                        [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| __self_0 |) |) |) ]
                      |)
                    ]));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::FrameInput::Create",
                      0
                    |) in
                  let _ := M.read (| γ1_0 |) in
                  let __self_0 :=
                    M.alloc (|
                      Ty.apply
                        (Ty.path "&")
                        []
                        [
                          Ty.apply
                            (Ty.path "alloc::boxed::Box")
                            []
                            [
                              Ty.path
                                "revm_interpreter::interpreter_action::create_inputs::CreateInputs";
                              Ty.path "alloc::alloc::Global"
                            ]
                        ],
                      M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                    |) in
                  Value.StructTuple
                    "revm_interpreter::interpreter_action::FrameInput::Create"
                    []
                    []
                    [
                      M.call_closure (|
                        Ty.apply
                          (Ty.path "alloc::boxed::Box")
                          []
                          [
                            Ty.path
                              "revm_interpreter::interpreter_action::create_inputs::CreateInputs";
                            Ty.path "alloc::alloc::Global"
                          ],
                        M.get_trait_method (|
                          "core::clone::Clone",
                          Ty.apply
                            (Ty.path "alloc::boxed::Box")
                            []
                            [
                              Ty.path
                                "revm_interpreter::interpreter_action::create_inputs::CreateInputs";
                              Ty.path "alloc::alloc::Global"
                            ],
                          [],
                          [],
                          "clone",
                          [],
                          []
                        |),
                        [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| __self_0 |) |) |) ]
                      |)
                    ]))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_revm_interpreter_interpreter_action_FrameInput.
  
  Module Impl_core_fmt_Debug_for_revm_interpreter_interpreter_action_FrameInput.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::FrameInput".
    
    (* Debug *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
              self
            |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.match_operator (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let _ :=
                    M.is_struct_tuple (|
                      γ,
                      "revm_interpreter::interpreter_action::FrameInput::Empty"
                    |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "write_str",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "Empty" |) |) |)
                    ]
                  |)));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::FrameInput::Call",
                      0
                    |) in
                  let _ := M.read (| γ1_0 |) in
                  let __self_0 :=
                    M.alloc (|
                      Ty.apply
                        (Ty.path "&")
                        []
                        [
                          Ty.apply
                            (Ty.path "alloc::boxed::Box")
                            []
                            [
                              Ty.path
                                "revm_interpreter::interpreter_action::call_inputs::CallInputs";
                              Ty.path "alloc::alloc::Global"
                            ]
                        ],
                      M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                    |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "debug_tuple_field1_finish",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "Call" |) |) |);
                      M.call_closure (|
                        Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                        M.pointer_coercion
                          M.PointerCoercion.Unsize
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [
                              Ty.apply
                                (Ty.path "&")
                                []
                                [
                                  Ty.apply
                                    (Ty.path "alloc::boxed::Box")
                                    []
                                    [
                                      Ty.path
                                        "revm_interpreter::interpreter_action::call_inputs::CallInputs";
                                      Ty.path "alloc::alloc::Global"
                                    ]
                                ]
                            ])
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, __self_0 |) |)
                          |)
                        ]
                      |)
                    ]
                  |)));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::FrameInput::Create",
                      0
                    |) in
                  let _ := M.read (| γ1_0 |) in
                  let __self_0 :=
                    M.alloc (|
                      Ty.apply
                        (Ty.path "&")
                        []
                        [
                          Ty.apply
                            (Ty.path "alloc::boxed::Box")
                            []
                            [
                              Ty.path
                                "revm_interpreter::interpreter_action::create_inputs::CreateInputs";
                              Ty.path "alloc::alloc::Global"
                            ]
                        ],
                      M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                    |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "debug_tuple_field1_finish",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "Create" |) |) |);
                      M.call_closure (|
                        Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                        M.pointer_coercion
                          M.PointerCoercion.Unsize
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [
                              Ty.apply
                                (Ty.path "&")
                                []
                                [
                                  Ty.apply
                                    (Ty.path "alloc::boxed::Box")
                                    []
                                    [
                                      Ty.path
                                        "revm_interpreter::interpreter_action::create_inputs::CreateInputs";
                                      Ty.path "alloc::alloc::Global"
                                    ]
                                ]
                            ])
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, __self_0 |) |)
                          |)
                        ]
                      |)
                    ]
                  |)))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Debug"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Debug_for_revm_interpreter_interpreter_action_FrameInput.
  
  Module Impl_core_marker_StructuralPartialEq_for_revm_interpreter_interpreter_action_FrameInput.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::FrameInput".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::StructuralPartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_StructuralPartialEq_for_revm_interpreter_interpreter_action_FrameInput.
  
  Module Impl_core_cmp_PartialEq_revm_interpreter_interpreter_action_FrameInput_for_revm_interpreter_interpreter_action_FrameInput.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::FrameInput".
    
    (* PartialEq *)
    Definition eq (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; other ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
              self
            |) in
          let other :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
              other
            |) in
          M.read (|
            let~ __self_discr : Ty.path "isize" :=
              M.call_closure (|
                Ty.path "isize",
                M.get_function (|
                  "core::intrinsics::discriminant_value",
                  [],
                  [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ]
                |),
                [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
              |) in
            let~ __arg1_discr : Ty.path "isize" :=
              M.call_closure (|
                Ty.path "isize",
                M.get_function (|
                  "core::intrinsics::discriminant_value",
                  [],
                  [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ]
                |),
                [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| other |) |) |) ]
              |) in
            M.alloc (|
              Ty.path "bool",
              LogicalOp.and (|
                M.call_closure (|
                  Ty.path "bool",
                  BinOp.eq,
                  [ M.read (| __self_discr |); M.read (| __arg1_discr |) ]
                |),
                ltac:(M.monadic
                  (M.match_operator (|
                    Ty.path "bool",
                    M.alloc (|
                      Ty.tuple
                        [
                          Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ];
                          Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ]
                        ],
                      Value.Tuple [ M.read (| self |); M.read (| other |) ]
                    |),
                    [
                      fun γ =>
                        ltac:(M.monadic
                          (let γ0_0 := M.SubPointer.get_tuple_field (| γ, 0 |) in
                          let γ0_1 := M.SubPointer.get_tuple_field (| γ, 1 |) in
                          let γ0_0 := M.deref (| M.read (| γ0_0 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_0,
                              "revm_interpreter::interpreter_action::FrameInput::Call",
                              0
                            |) in
                          let _ := M.read (| γ2_0 |) in
                          let __self_0 :=
                            M.alloc (|
                              Ty.apply
                                (Ty.path "&")
                                []
                                [
                                  Ty.apply
                                    (Ty.path "alloc::boxed::Box")
                                    []
                                    [
                                      Ty.path
                                        "revm_interpreter::interpreter_action::call_inputs::CallInputs";
                                      Ty.path "alloc::alloc::Global"
                                    ]
                                ],
                              M.borrow (| Pointer.Kind.Ref, γ2_0 |)
                            |) in
                          let γ0_1 := M.deref (| M.read (| γ0_1 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_1,
                              "revm_interpreter::interpreter_action::FrameInput::Call",
                              0
                            |) in
                          let _ := M.read (| γ2_0 |) in
                          let __arg1_0 :=
                            M.alloc (|
                              Ty.apply
                                (Ty.path "&")
                                []
                                [
                                  Ty.apply
                                    (Ty.path "alloc::boxed::Box")
                                    []
                                    [
                                      Ty.path
                                        "revm_interpreter::interpreter_action::call_inputs::CallInputs";
                                      Ty.path "alloc::alloc::Global"
                                    ]
                                ],
                              M.borrow (| Pointer.Kind.Ref, γ2_0 |)
                            |) in
                          M.call_closure (|
                            Ty.path "bool",
                            M.get_trait_method (|
                              "core::cmp::PartialEq",
                              Ty.apply
                                (Ty.path "&")
                                []
                                [
                                  Ty.apply
                                    (Ty.path "alloc::boxed::Box")
                                    []
                                    [
                                      Ty.path
                                        "revm_interpreter::interpreter_action::call_inputs::CallInputs";
                                      Ty.path "alloc::alloc::Global"
                                    ]
                                ],
                              [],
                              [
                                Ty.apply
                                  (Ty.path "&")
                                  []
                                  [
                                    Ty.apply
                                      (Ty.path "alloc::boxed::Box")
                                      []
                                      [
                                        Ty.path
                                          "revm_interpreter::interpreter_action::call_inputs::CallInputs";
                                        Ty.path "alloc::alloc::Global"
                                      ]
                                  ]
                              ],
                              "eq",
                              [],
                              []
                            |),
                            [
                              M.borrow (| Pointer.Kind.Ref, __self_0 |);
                              M.borrow (| Pointer.Kind.Ref, __arg1_0 |)
                            ]
                          |)));
                      fun γ =>
                        ltac:(M.monadic
                          (let γ0_0 := M.SubPointer.get_tuple_field (| γ, 0 |) in
                          let γ0_1 := M.SubPointer.get_tuple_field (| γ, 1 |) in
                          let γ0_0 := M.deref (| M.read (| γ0_0 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_0,
                              "revm_interpreter::interpreter_action::FrameInput::Create",
                              0
                            |) in
                          let _ := M.read (| γ2_0 |) in
                          let __self_0 :=
                            M.alloc (|
                              Ty.apply
                                (Ty.path "&")
                                []
                                [
                                  Ty.apply
                                    (Ty.path "alloc::boxed::Box")
                                    []
                                    [
                                      Ty.path
                                        "revm_interpreter::interpreter_action::create_inputs::CreateInputs";
                                      Ty.path "alloc::alloc::Global"
                                    ]
                                ],
                              M.borrow (| Pointer.Kind.Ref, γ2_0 |)
                            |) in
                          let γ0_1 := M.deref (| M.read (| γ0_1 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_1,
                              "revm_interpreter::interpreter_action::FrameInput::Create",
                              0
                            |) in
                          let _ := M.read (| γ2_0 |) in
                          let __arg1_0 :=
                            M.alloc (|
                              Ty.apply
                                (Ty.path "&")
                                []
                                [
                                  Ty.apply
                                    (Ty.path "alloc::boxed::Box")
                                    []
                                    [
                                      Ty.path
                                        "revm_interpreter::interpreter_action::create_inputs::CreateInputs";
                                      Ty.path "alloc::alloc::Global"
                                    ]
                                ],
                              M.borrow (| Pointer.Kind.Ref, γ2_0 |)
                            |) in
                          M.call_closure (|
                            Ty.path "bool",
                            M.get_trait_method (|
                              "core::cmp::PartialEq",
                              Ty.apply
                                (Ty.path "&")
                                []
                                [
                                  Ty.apply
                                    (Ty.path "alloc::boxed::Box")
                                    []
                                    [
                                      Ty.path
                                        "revm_interpreter::interpreter_action::create_inputs::CreateInputs";
                                      Ty.path "alloc::alloc::Global"
                                    ]
                                ],
                              [],
                              [
                                Ty.apply
                                  (Ty.path "&")
                                  []
                                  [
                                    Ty.apply
                                      (Ty.path "alloc::boxed::Box")
                                      []
                                      [
                                        Ty.path
                                          "revm_interpreter::interpreter_action::create_inputs::CreateInputs";
                                        Ty.path "alloc::alloc::Global"
                                      ]
                                  ]
                              ],
                              "eq",
                              [],
                              []
                            |),
                            [
                              M.borrow (| Pointer.Kind.Ref, __self_0 |);
                              M.borrow (| Pointer.Kind.Ref, __arg1_0 |)
                            ]
                          |)));
                      fun γ => ltac:(M.monadic (Value.Bool true))
                    ]
                  |)))
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::PartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ]
        Self
        (* Instance *) [ ("eq", InstanceField.Method eq) ].
  End Impl_core_cmp_PartialEq_revm_interpreter_interpreter_action_FrameInput_for_revm_interpreter_interpreter_action_FrameInput.
  
  Module Impl_core_cmp_Eq_for_revm_interpreter_interpreter_action_FrameInput.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::FrameInput".
    
    (* Eq *)
    Definition assert_receiver_is_total_eq
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
              self
            |) in
          M.match_operator (|
            Ty.tuple [],
            Value.DeclaredButUndefined,
            [
              fun γ =>
                ltac:(M.monadic
                  (M.match_operator (|
                    Ty.tuple [],
                    Value.DeclaredButUndefined,
                    [ fun γ => ltac:(M.monadic (Value.Tuple [])) ]
                  |)))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::Eq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *)
        [ ("assert_receiver_is_total_eq", InstanceField.Method assert_receiver_is_total_eq) ].
  End Impl_core_cmp_Eq_for_revm_interpreter_interpreter_action_FrameInput.
  
  (* StructRecord
    {
      name := "FrameInit";
      const_params := [];
      ty_params := [];
      fields :=
        [
          ("depth", Ty.path "usize");
          ("memory", Ty.path "revm_interpreter::interpreter::shared_memory::SharedMemory");
          ("frame_input", Ty.path "revm_interpreter::interpreter_action::FrameInput")
        ];
    } *)
  
  Module Impl_core_clone_Clone_for_revm_interpreter_interpreter_action_FrameInit.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::FrameInit".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::FrameInit" ],
              self
            |) in
          Value.mkStructRecord
            "revm_interpreter::interpreter_action::FrameInit"
            []
            []
            [
              ("depth",
                M.call_closure (|
                  Ty.path "usize",
                  M.get_trait_method (|
                    "core::clone::Clone",
                    Ty.path "usize",
                    [],
                    [],
                    "clone",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.deref (|
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "revm_interpreter::interpreter_action::FrameInit",
                            "depth"
                          |)
                        |)
                      |)
                    |)
                  ]
                |));
              ("memory",
                M.call_closure (|
                  Ty.path "revm_interpreter::interpreter::shared_memory::SharedMemory",
                  M.get_trait_method (|
                    "core::clone::Clone",
                    Ty.path "revm_interpreter::interpreter::shared_memory::SharedMemory",
                    [],
                    [],
                    "clone",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.deref (|
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "revm_interpreter::interpreter_action::FrameInit",
                            "memory"
                          |)
                        |)
                      |)
                    |)
                  ]
                |));
              ("frame_input",
                M.call_closure (|
                  Ty.path "revm_interpreter::interpreter_action::FrameInput",
                  M.get_trait_method (|
                    "core::clone::Clone",
                    Ty.path "revm_interpreter::interpreter_action::FrameInput",
                    [],
                    [],
                    "clone",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.deref (|
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "revm_interpreter::interpreter_action::FrameInit",
                            "frame_input"
                          |)
                        |)
                      |)
                    |)
                  ]
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_revm_interpreter_interpreter_action_FrameInit.
  
  Module Impl_core_fmt_Debug_for_revm_interpreter_interpreter_action_FrameInit.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::FrameInit".
    
    (* Debug *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::FrameInit" ],
              self
            |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.call_closure (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            M.get_associated_function (|
              Ty.path "core::fmt::Formatter",
              "debug_struct_field3_finish",
              [],
              []
            |),
            [
              M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "FrameInit" |) |) |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "depth" |) |) |);
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply (Ty.path "&") [] [ Ty.path "usize" ])
                  (Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "revm_interpreter::interpreter_action::FrameInit",
                          "depth"
                        |)
                      |)
                    |)
                  |)
                ]
              |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "memory" |) |) |);
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply
                    (Ty.path "&")
                    []
                    [ Ty.path "revm_interpreter::interpreter::shared_memory::SharedMemory" ])
                  (Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "revm_interpreter::interpreter_action::FrameInit",
                          "memory"
                        |)
                      |)
                    |)
                  |)
                ]
              |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "frame_input" |) |) |);
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply
                    (Ty.path "&")
                    []
                    [
                      Ty.apply
                        (Ty.path "&")
                        []
                        [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ]
                    ])
                  (Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.alloc (|
                          Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.SubPointer.get_struct_record_field (|
                              M.deref (| M.read (| self |) |),
                              "revm_interpreter::interpreter_action::FrameInit",
                              "frame_input"
                            |)
                          |)
                        |)
                      |)
                    |)
                  |)
                ]
              |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Debug"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Debug_for_revm_interpreter_interpreter_action_FrameInit.
  
  Module Impl_core_marker_StructuralPartialEq_for_revm_interpreter_interpreter_action_FrameInit.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::FrameInit".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::StructuralPartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_StructuralPartialEq_for_revm_interpreter_interpreter_action_FrameInit.
  
  Module Impl_core_cmp_PartialEq_revm_interpreter_interpreter_action_FrameInit_for_revm_interpreter_interpreter_action_FrameInit.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::FrameInit".
    
    (* PartialEq *)
    Definition eq (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; other ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::FrameInit" ],
              self
            |) in
          let other :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::FrameInit" ],
              other
            |) in
          LogicalOp.and (|
            LogicalOp.and (|
              M.call_closure (|
                Ty.path "bool",
                BinOp.eq,
                [
                  M.read (|
                    M.SubPointer.get_struct_record_field (|
                      M.deref (| M.read (| self |) |),
                      "revm_interpreter::interpreter_action::FrameInit",
                      "depth"
                    |)
                  |);
                  M.read (|
                    M.SubPointer.get_struct_record_field (|
                      M.deref (| M.read (| other |) |),
                      "revm_interpreter::interpreter_action::FrameInit",
                      "depth"
                    |)
                  |)
                ]
              |),
              ltac:(M.monadic
                (M.call_closure (|
                  Ty.path "bool",
                  M.get_trait_method (|
                    "core::cmp::PartialEq",
                    Ty.path "revm_interpreter::interpreter::shared_memory::SharedMemory",
                    [],
                    [ Ty.path "revm_interpreter::interpreter::shared_memory::SharedMemory" ],
                    "eq",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.SubPointer.get_struct_record_field (|
                        M.deref (| M.read (| self |) |),
                        "revm_interpreter::interpreter_action::FrameInit",
                        "memory"
                      |)
                    |);
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.SubPointer.get_struct_record_field (|
                        M.deref (| M.read (| other |) |),
                        "revm_interpreter::interpreter_action::FrameInit",
                        "memory"
                      |)
                    |)
                  ]
                |)))
            |),
            ltac:(M.monadic
              (M.call_closure (|
                Ty.path "bool",
                M.get_trait_method (|
                  "core::cmp::PartialEq",
                  Ty.path "revm_interpreter::interpreter_action::FrameInput",
                  [],
                  [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
                  "eq",
                  [],
                  []
                |),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.SubPointer.get_struct_record_field (|
                      M.deref (| M.read (| self |) |),
                      "revm_interpreter::interpreter_action::FrameInit",
                      "frame_input"
                    |)
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.SubPointer.get_struct_record_field (|
                      M.deref (| M.read (| other |) |),
                      "revm_interpreter::interpreter_action::FrameInit",
                      "frame_input"
                    |)
                  |)
                ]
              |)))
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::PartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) [ Ty.path "revm_interpreter::interpreter_action::FrameInit" ]
        Self
        (* Instance *) [ ("eq", InstanceField.Method eq) ].
  End Impl_core_cmp_PartialEq_revm_interpreter_interpreter_action_FrameInit_for_revm_interpreter_interpreter_action_FrameInit.
  
  Module Impl_core_cmp_Eq_for_revm_interpreter_interpreter_action_FrameInit.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::FrameInit".
    
    (* Eq *)
    Definition assert_receiver_is_total_eq
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::FrameInit" ],
              self
            |) in
          M.match_operator (|
            Ty.tuple [],
            Value.DeclaredButUndefined,
            [
              fun γ =>
                ltac:(M.monadic
                  (M.match_operator (|
                    Ty.tuple [],
                    Value.DeclaredButUndefined,
                    [
                      fun γ =>
                        ltac:(M.monadic
                          (M.match_operator (|
                            Ty.tuple [],
                            Value.DeclaredButUndefined,
                            [ fun γ => ltac:(M.monadic (Value.Tuple [])) ]
                          |)))
                    ]
                  |)))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::Eq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *)
        [ ("assert_receiver_is_total_eq", InstanceField.Method assert_receiver_is_total_eq) ].
  End Impl_core_cmp_Eq_for_revm_interpreter_interpreter_action_FrameInit.
  
  Module Impl_core_convert_AsMut_revm_interpreter_interpreter_action_FrameInput_for_revm_interpreter_interpreter_action_FrameInput.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::FrameInput".
    
    (*
        fn as_mut(&mut self) -> &mut Self {
            self
        }
    *)
    Definition as_mut (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
              self
            |) in
          M.borrow (|
            Pointer.Kind.MutRef,
            M.deref (| M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |) |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::convert::AsMut"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ]
        Self
        (* Instance *) [ ("as_mut", InstanceField.Method as_mut) ].
  End Impl_core_convert_AsMut_revm_interpreter_interpreter_action_FrameInput_for_revm_interpreter_interpreter_action_FrameInput.
  
  (*
  Enum InterpreterAction
  {
    const_params := [];
    ty_params := [];
    variants :=
      [
        {
          name := "NewFrame";
          item := StructTuple [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ];
        };
        {
          name := "Return";
          item := StructTuple [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ];
        }
      ];
  }
  *)
  
  Axiom IsDiscriminant_InterpreterAction_NewFrame :
    M.IsDiscriminant "revm_interpreter::interpreter_action::InterpreterAction::NewFrame" 0.
  Axiom IsDiscriminant_InterpreterAction_Return :
    M.IsDiscriminant "revm_interpreter::interpreter_action::InterpreterAction::Return" 1.
  
  Module Impl_core_clone_Clone_for_revm_interpreter_interpreter_action_InterpreterAction.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::InterpreterAction".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ],
              self
            |) in
          M.match_operator (|
            Ty.path "revm_interpreter::interpreter_action::InterpreterAction",
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::InterpreterAction::NewFrame",
                      0
                    |) in
                  let _ := M.read (| γ1_0 |) in
                  let __self_0 :=
                    M.alloc (|
                      Ty.apply
                        (Ty.path "&")
                        []
                        [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
                      M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                    |) in
                  Value.StructTuple
                    "revm_interpreter::interpreter_action::InterpreterAction::NewFrame"
                    []
                    []
                    [
                      M.call_closure (|
                        Ty.path "revm_interpreter::interpreter_action::FrameInput",
                        M.get_trait_method (|
                          "core::clone::Clone",
                          Ty.path "revm_interpreter::interpreter_action::FrameInput",
                          [],
                          [],
                          "clone",
                          [],
                          []
                        |),
                        [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| __self_0 |) |) |) ]
                      |)
                    ]));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::InterpreterAction::Return",
                      0
                    |) in
                  let _ := M.read (| γ1_0 |) in
                  let __self_0 :=
                    M.alloc (|
                      Ty.apply
                        (Ty.path "&")
                        []
                        [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ],
                      M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                    |) in
                  Value.StructTuple
                    "revm_interpreter::interpreter_action::InterpreterAction::Return"
                    []
                    []
                    [
                      M.call_closure (|
                        Ty.path "revm_interpreter::interpreter::InterpreterResult",
                        M.get_trait_method (|
                          "core::clone::Clone",
                          Ty.path "revm_interpreter::interpreter::InterpreterResult",
                          [],
                          [],
                          "clone",
                          [],
                          []
                        |),
                        [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| __self_0 |) |) |) ]
                      |)
                    ]))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_revm_interpreter_interpreter_action_InterpreterAction.
  
  Module Impl_core_fmt_Debug_for_revm_interpreter_interpreter_action_InterpreterAction.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::InterpreterAction".
    
    (* Debug *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ],
              self
            |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.match_operator (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::InterpreterAction::NewFrame",
                      0
                    |) in
                  let _ := M.read (| γ1_0 |) in
                  let __self_0 :=
                    M.alloc (|
                      Ty.apply
                        (Ty.path "&")
                        []
                        [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
                      M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                    |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "debug_tuple_field1_finish",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "NewFrame" |) |) |);
                      M.call_closure (|
                        Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                        M.pointer_coercion
                          M.PointerCoercion.Unsize
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [
                              Ty.apply
                                (Ty.path "&")
                                []
                                [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ]
                            ])
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, __self_0 |) |)
                          |)
                        ]
                      |)
                    ]
                  |)));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::InterpreterAction::Return",
                      0
                    |) in
                  let _ := M.read (| γ1_0 |) in
                  let __self_0 :=
                    M.alloc (|
                      Ty.apply
                        (Ty.path "&")
                        []
                        [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ],
                      M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                    |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "debug_tuple_field1_finish",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "Return" |) |) |);
                      M.call_closure (|
                        Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                        M.pointer_coercion
                          M.PointerCoercion.Unsize
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [
                              Ty.apply
                                (Ty.path "&")
                                []
                                [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ]
                            ])
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, __self_0 |) |)
                          |)
                        ]
                      |)
                    ]
                  |)))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Debug"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Debug_for_revm_interpreter_interpreter_action_InterpreterAction.
  
  Module Impl_core_marker_StructuralPartialEq_for_revm_interpreter_interpreter_action_InterpreterAction.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::InterpreterAction".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::StructuralPartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_StructuralPartialEq_for_revm_interpreter_interpreter_action_InterpreterAction.
  
  Module Impl_core_cmp_PartialEq_revm_interpreter_interpreter_action_InterpreterAction_for_revm_interpreter_interpreter_action_InterpreterAction.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::InterpreterAction".
    
    (* PartialEq *)
    Definition eq (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; other ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ],
              self
            |) in
          let other :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ],
              other
            |) in
          M.read (|
            let~ __self_discr : Ty.path "isize" :=
              M.call_closure (|
                Ty.path "isize",
                M.get_function (|
                  "core::intrinsics::discriminant_value",
                  [],
                  [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ]
                |),
                [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
              |) in
            let~ __arg1_discr : Ty.path "isize" :=
              M.call_closure (|
                Ty.path "isize",
                M.get_function (|
                  "core::intrinsics::discriminant_value",
                  [],
                  [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ]
                |),
                [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| other |) |) |) ]
              |) in
            M.alloc (|
              Ty.path "bool",
              LogicalOp.and (|
                M.call_closure (|
                  Ty.path "bool",
                  BinOp.eq,
                  [ M.read (| __self_discr |); M.read (| __arg1_discr |) ]
                |),
                ltac:(M.monadic
                  (M.match_operator (|
                    Ty.path "bool",
                    M.alloc (|
                      Ty.tuple
                        [
                          Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ];
                          Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ]
                        ],
                      Value.Tuple [ M.read (| self |); M.read (| other |) ]
                    |),
                    [
                      fun γ =>
                        ltac:(M.monadic
                          (let γ0_0 := M.SubPointer.get_tuple_field (| γ, 0 |) in
                          let γ0_1 := M.SubPointer.get_tuple_field (| γ, 1 |) in
                          let γ0_0 := M.deref (| M.read (| γ0_0 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_0,
                              "revm_interpreter::interpreter_action::InterpreterAction::NewFrame",
                              0
                            |) in
                          let _ := M.read (| γ2_0 |) in
                          let __self_0 :=
                            M.alloc (|
                              Ty.apply
                                (Ty.path "&")
                                []
                                [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
                              M.borrow (| Pointer.Kind.Ref, γ2_0 |)
                            |) in
                          let γ0_1 := M.deref (| M.read (| γ0_1 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_1,
                              "revm_interpreter::interpreter_action::InterpreterAction::NewFrame",
                              0
                            |) in
                          let _ := M.read (| γ2_0 |) in
                          let __arg1_0 :=
                            M.alloc (|
                              Ty.apply
                                (Ty.path "&")
                                []
                                [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
                              M.borrow (| Pointer.Kind.Ref, γ2_0 |)
                            |) in
                          M.call_closure (|
                            Ty.path "bool",
                            M.get_trait_method (|
                              "core::cmp::PartialEq",
                              Ty.apply
                                (Ty.path "&")
                                []
                                [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ],
                              [],
                              [
                                Ty.apply
                                  (Ty.path "&")
                                  []
                                  [ Ty.path "revm_interpreter::interpreter_action::FrameInput" ]
                              ],
                              "eq",
                              [],
                              []
                            |),
                            [
                              M.borrow (| Pointer.Kind.Ref, __self_0 |);
                              M.borrow (| Pointer.Kind.Ref, __arg1_0 |)
                            ]
                          |)));
                      fun γ =>
                        ltac:(M.monadic
                          (let γ0_0 := M.SubPointer.get_tuple_field (| γ, 0 |) in
                          let γ0_1 := M.SubPointer.get_tuple_field (| γ, 1 |) in
                          let γ0_0 := M.deref (| M.read (| γ0_0 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_0,
                              "revm_interpreter::interpreter_action::InterpreterAction::Return",
                              0
                            |) in
                          let _ := M.read (| γ2_0 |) in
                          let __self_0 :=
                            M.alloc (|
                              Ty.apply
                                (Ty.path "&")
                                []
                                [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ],
                              M.borrow (| Pointer.Kind.Ref, γ2_0 |)
                            |) in
                          let γ0_1 := M.deref (| M.read (| γ0_1 |) |) in
                          let γ2_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ0_1,
                              "revm_interpreter::interpreter_action::InterpreterAction::Return",
                              0
                            |) in
                          let _ := M.read (| γ2_0 |) in
                          let __arg1_0 :=
                            M.alloc (|
                              Ty.apply
                                (Ty.path "&")
                                []
                                [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ],
                              M.borrow (| Pointer.Kind.Ref, γ2_0 |)
                            |) in
                          M.call_closure (|
                            Ty.path "bool",
                            M.get_trait_method (|
                              "core::cmp::PartialEq",
                              Ty.apply
                                (Ty.path "&")
                                []
                                [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ],
                              [],
                              [
                                Ty.apply
                                  (Ty.path "&")
                                  []
                                  [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ]
                              ],
                              "eq",
                              [],
                              []
                            |),
                            [
                              M.borrow (| Pointer.Kind.Ref, __self_0 |);
                              M.borrow (| Pointer.Kind.Ref, __arg1_0 |)
                            ]
                          |)));
                      fun γ =>
                        ltac:(M.monadic
                          (M.never_to_any (|
                            M.call_closure (|
                              Ty.path "never",
                              M.get_function (| "core::intrinsics::unreachable", [], [] |),
                              []
                            |)
                          |)))
                    ]
                  |)))
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::PartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *)
        [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ]
        Self
        (* Instance *) [ ("eq", InstanceField.Method eq) ].
  End Impl_core_cmp_PartialEq_revm_interpreter_interpreter_action_InterpreterAction_for_revm_interpreter_interpreter_action_InterpreterAction.
  
  Module Impl_core_cmp_Eq_for_revm_interpreter_interpreter_action_InterpreterAction.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::InterpreterAction".
    
    (* Eq *)
    Definition assert_receiver_is_total_eq
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ],
              self
            |) in
          M.match_operator (|
            Ty.tuple [],
            Value.DeclaredButUndefined,
            [
              fun γ =>
                ltac:(M.monadic
                  (M.match_operator (|
                    Ty.tuple [],
                    Value.DeclaredButUndefined,
                    [ fun γ => ltac:(M.monadic (Value.Tuple [])) ]
                  |)))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::Eq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *)
        [ ("assert_receiver_is_total_eq", InstanceField.Method assert_receiver_is_total_eq) ].
  End Impl_core_cmp_Eq_for_revm_interpreter_interpreter_action_InterpreterAction.
  
  Module Impl_revm_interpreter_interpreter_action_InterpreterAction.
    Definition Self : Ty.t := Ty.path "revm_interpreter::interpreter_action::InterpreterAction".
    
    (*
        pub fn is_call(&self) -> bool {
            matches!(self, InterpreterAction::NewFrame(FrameInput::Call(..)))
        }
    *)
    Definition is_call (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ],
              self
            |) in
          M.match_operator (|
            Ty.path "bool",
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::InterpreterAction::NewFrame",
                      0
                    |) in
                  let _ :=
                    M.is_struct_tuple (|
                      γ1_0,
                      "revm_interpreter::interpreter_action::FrameInput::Call"
                    |) in
                  Value.Bool true));
              fun γ => ltac:(M.monadic (Value.Bool false))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_call : M.IsAssociatedFunction.C Self "is_call" is_call.
    Proof.
    Admitted.
    Global Typeclasses Opaque is_call.
    
    (*
        pub fn is_create(&self) -> bool {
            matches!(self, InterpreterAction::NewFrame(FrameInput::Create(..)))
        }
    *)
    Definition is_create (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ],
              self
            |) in
          M.match_operator (|
            Ty.path "bool",
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::InterpreterAction::NewFrame",
                      0
                    |) in
                  let _ :=
                    M.is_struct_tuple (|
                      γ1_0,
                      "revm_interpreter::interpreter_action::FrameInput::Create"
                    |) in
                  Value.Bool true));
              fun γ => ltac:(M.monadic (Value.Bool false))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_create :
      M.IsAssociatedFunction.C Self "is_create" is_create.
    Proof.
    Admitted.
    Global Typeclasses Opaque is_create.
    
    (*
        pub fn is_return(&self) -> bool {
            matches!(self, InterpreterAction::Return { .. })
        }
    *)
    Definition is_return (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ],
              self
            |) in
          M.match_operator (|
            Ty.path "bool",
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let _ :=
                    M.is_struct_tuple (|
                      γ,
                      "revm_interpreter::interpreter_action::InterpreterAction::Return"
                    |) in
                  Value.Bool true));
              fun γ => ltac:(M.monadic (Value.Bool false))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_is_return :
      M.IsAssociatedFunction.C Self "is_return" is_return.
    Proof.
    Admitted.
    Global Typeclasses Opaque is_return.
    
    (*
        pub fn gas_mut(&mut self) -> Option<&mut Gas> {
            match self {
                InterpreterAction::Return(result) => Some(&mut result.gas),
                _ => None,
            }
        }
    *)
    Definition gas_mut (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ],
              self
            |) in
          M.match_operator (|
            Ty.apply
              (Ty.path "core::option::Option")
              []
              [ Ty.apply (Ty.path "&mut") [] [ Ty.path "revm_interpreter::gas::Gas" ] ],
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::InterpreterAction::Return",
                      0
                    |) in
                  let _ := M.read (| γ1_0 |) in
                  let result :=
                    M.alloc (|
                      Ty.apply
                        (Ty.path "&mut")
                        []
                        [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ],
                      M.borrow (| Pointer.Kind.MutRef, γ1_0 |)
                    |) in
                  Value.StructTuple
                    "core::option::Option::Some"
                    []
                    [ Ty.apply (Ty.path "&mut") [] [ Ty.path "revm_interpreter::gas::Gas" ] ]
                    [
                      M.borrow (|
                        Pointer.Kind.MutRef,
                        M.deref (|
                          M.borrow (|
                            Pointer.Kind.MutRef,
                            M.SubPointer.get_struct_record_field (|
                              M.deref (| M.read (| result |) |),
                              "revm_interpreter::interpreter::InterpreterResult",
                              "gas"
                            |)
                          |)
                        |)
                      |)
                    ]));
              fun γ =>
                ltac:(M.monadic
                  (Value.StructTuple
                    "core::option::Option::None"
                    []
                    [ Ty.apply (Ty.path "&mut") [] [ Ty.path "revm_interpreter::gas::Gas" ] ]
                    []))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_gas_mut : M.IsAssociatedFunction.C Self "gas_mut" gas_mut.
    Proof.
    Admitted.
    Global Typeclasses Opaque gas_mut.
    
    (*
        pub fn into_result_return(self) -> Option<InterpreterResult> {
            match self {
                InterpreterAction::Return(result) => Some(result),
                _ => None,
            }
        }
    *)
    Definition into_result_return (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.path "revm_interpreter::interpreter_action::InterpreterAction", self |) in
          M.match_operator (|
            Ty.apply
              (Ty.path "core::option::Option")
              []
              [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ],
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ0_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::InterpreterAction::Return",
                      0
                    |) in
                  let result :=
                    M.copy (| Ty.path "revm_interpreter::interpreter::InterpreterResult", γ0_0 |) in
                  Value.StructTuple
                    "core::option::Option::Some"
                    []
                    [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ]
                    [ M.read (| result |) ]));
              fun γ =>
                ltac:(M.monadic
                  (Value.StructTuple
                    "core::option::Option::None"
                    []
                    [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ]
                    []))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_into_result_return :
      M.IsAssociatedFunction.C Self "into_result_return" into_result_return.
    Proof.
    Admitted.
    Global Typeclasses Opaque into_result_return.
    
    (*
        pub fn instruction_result(&self) -> Option<InstructionResult> {
            match self {
                InterpreterAction::Return(result) => Some(result.result),
                _ => None,
            }
        }
    *)
    Definition instruction_result (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_interpreter::interpreter_action::InterpreterAction" ],
              self
            |) in
          M.match_operator (|
            Ty.apply
              (Ty.path "core::option::Option")
              []
              [ Ty.path "revm_interpreter::instruction_result::InstructionResult" ],
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "revm_interpreter::interpreter_action::InterpreterAction::Return",
                      0
                    |) in
                  let _ := M.read (| γ1_0 |) in
                  let result :=
                    M.alloc (|
                      Ty.apply
                        (Ty.path "&")
                        []
                        [ Ty.path "revm_interpreter::interpreter::InterpreterResult" ],
                      M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                    |) in
                  Value.StructTuple
                    "core::option::Option::Some"
                    []
                    [ Ty.path "revm_interpreter::instruction_result::InstructionResult" ]
                    [
                      M.read (|
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| result |) |),
                          "revm_interpreter::interpreter::InterpreterResult",
                          "result"
                        |)
                      |)
                    ]));
              fun γ =>
                ltac:(M.monadic
                  (Value.StructTuple
                    "core::option::Option::None"
                    []
                    [ Ty.path "revm_interpreter::instruction_result::InstructionResult" ]
                    []))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_instruction_result :
      M.IsAssociatedFunction.C Self "instruction_result" instruction_result.
    Proof.
    Admitted.
    Global Typeclasses Opaque instruction_result.
    
    (*
        pub fn new_frame(frame_input: FrameInput) -> Self {
            Self::NewFrame(frame_input)
        }
    *)
    Definition new_frame (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ frame_input ] =>
        ltac:(M.monadic
          (let frame_input :=
            M.alloc (| Ty.path "revm_interpreter::interpreter_action::FrameInput", frame_input |) in
          Value.StructTuple
            "revm_interpreter::interpreter_action::InterpreterAction::NewFrame"
            []
            []
            [ M.read (| frame_input |) ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_new_frame :
      M.IsAssociatedFunction.C Self "new_frame" new_frame.
    Proof.
    Admitted.
    Global Typeclasses Opaque new_frame.
    
    (*
        pub fn new_halt(result: InstructionResult, gas: Gas) -> Self {
            Self::Return(InterpreterResult::new(result, Bytes::new(), gas))
        }
    *)
    Definition new_halt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ result; gas ] =>
        ltac:(M.monadic
          (let result :=
            M.alloc (|
              Ty.path "revm_interpreter::instruction_result::InstructionResult",
              result
            |) in
          let gas := M.alloc (| Ty.path "revm_interpreter::gas::Gas", gas |) in
          Value.StructTuple
            "revm_interpreter::interpreter_action::InterpreterAction::Return"
            []
            []
            [
              M.call_closure (|
                Ty.path "revm_interpreter::interpreter::InterpreterResult",
                M.get_associated_function (|
                  Ty.path "revm_interpreter::interpreter::InterpreterResult",
                  "new",
                  [],
                  []
                |),
                [
                  M.read (| result |);
                  M.call_closure (|
                    Ty.path "alloy_primitives::bytes_::Bytes",
                    M.get_associated_function (|
                      Ty.path "alloy_primitives::bytes_::Bytes",
                      "new",
                      [],
                      []
                    |),
                    []
                  |);
                  M.read (| gas |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_new_halt : M.IsAssociatedFunction.C Self "new_halt" new_halt.
    Proof.
    Admitted.
    Global Typeclasses Opaque new_halt.
    
    (*
        pub fn new_return(result: InstructionResult, output: Bytes, gas: Gas) -> Self {
            Self::Return(InterpreterResult::new(result, output, gas))
        }
    *)
    Definition new_return (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ result; output; gas ] =>
        ltac:(M.monadic
          (let result :=
            M.alloc (|
              Ty.path "revm_interpreter::instruction_result::InstructionResult",
              result
            |) in
          let output := M.alloc (| Ty.path "alloy_primitives::bytes_::Bytes", output |) in
          let gas := M.alloc (| Ty.path "revm_interpreter::gas::Gas", gas |) in
          Value.StructTuple
            "revm_interpreter::interpreter_action::InterpreterAction::Return"
            []
            []
            [
              M.call_closure (|
                Ty.path "revm_interpreter::interpreter::InterpreterResult",
                M.get_associated_function (|
                  Ty.path "revm_interpreter::interpreter::InterpreterResult",
                  "new",
                  [],
                  []
                |),
                [ M.read (| result |); M.read (| output |); M.read (| gas |) ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_new_return :
      M.IsAssociatedFunction.C Self "new_return" new_return.
    Proof.
    Admitted.
    Global Typeclasses Opaque new_return.
    
    (*
        pub fn new_stop() -> Self {
            Self::Return(InterpreterResult::new(
                InstructionResult::Stop,
                Bytes::new(),
                Gas::new(0),
            ))
        }
    *)
    Definition new_stop (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [] =>
        ltac:(M.monadic
          (Value.StructTuple
            "revm_interpreter::interpreter_action::InterpreterAction::Return"
            []
            []
            [
              M.call_closure (|
                Ty.path "revm_interpreter::interpreter::InterpreterResult",
                M.get_associated_function (|
                  Ty.path "revm_interpreter::interpreter::InterpreterResult",
                  "new",
                  [],
                  []
                |),
                [
                  Value.StructTuple
                    "revm_interpreter::instruction_result::InstructionResult::Stop"
                    []
                    []
                    [];
                  M.call_closure (|
                    Ty.path "alloy_primitives::bytes_::Bytes",
                    M.get_associated_function (|
                      Ty.path "alloy_primitives::bytes_::Bytes",
                      "new",
                      [],
                      []
                    |),
                    []
                  |);
                  M.call_closure (|
                    Ty.path "revm_interpreter::gas::Gas",
                    M.get_associated_function (|
                      Ty.path "revm_interpreter::gas::Gas",
                      "new",
                      [],
                      []
                    |),
                    [ Value.Integer IntegerKind.U64 0 ]
                  |)
                ]
              |)
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_new_stop : M.IsAssociatedFunction.C Self "new_stop" new_stop.
    Proof.
    Admitted.
    Global Typeclasses Opaque new_stop.
  End Impl_revm_interpreter_interpreter_action_InterpreterAction.
End interpreter_action.
