(* Generated by Jinja from solana_program_token/interface/links/state.v.jinja2 - DO NOT EDIT *)
Require Import RocqOfRust.RocqOfRust.
Require Import RocqOfRust.links.M.
Require Import anza_xyz_solana_sdk.address.links.lib.
Require Import anza_xyz_solana_sdk.program_error.links.lib.
Require Import anza_xyz_solana_sdk.program_option.links.lib.
Require Import anza_xyz_solana_sdk.program_pack.links.lib.
Require Import solana_program_token.interface.state.

(*
  pub enum AccountState {
      Uninitialized,
      Initialized,
      Frozen,
  }
*)
Module AccountState.
  Inductive t : Set :=
  | Uninitialized
  | Initialized
  | Frozen
  .

  Global Instance IsLink : Link t := {
    Φ := Ty.path "spl_token_interface::state::AccountState";
    φ x :=
      match x with
      | Uninitialized =>
          Value.StructTuple "spl_token_interface::state::AccountState::Uninitialized" [] [] []
      | Initialized =>
          Value.StructTuple "spl_token_interface::state::AccountState::Initialized" [] [] []
      | Frozen =>
          Value.StructTuple "spl_token_interface::state::AccountState::Frozen" [] [] []
      end
  }.

  Global Instance IsOfTy : OfTy.C (Ty.path "spl_token_interface::state::AccountState") :=
  {
    A := t;
    eq := eq_refl;
  }.

  Global Instance IsOfValueWith_Uninitialized :
    OfValueWith.C t (Value.StructTuple "spl_token_interface::state::AccountState::Uninitialized" [] [] []) :=
  {
    value := Uninitialized;
    eq := eq_refl;
  }.

  Global Instance IsOfValue_Uninitialized :
    OfValue.C (Value.StructTuple "spl_token_interface::state::AccountState::Uninitialized" [] [] []) :=
  {
    value := Uninitialized;
    eq := eq_refl;
  }.

  Global Instance IsOfValueWith_Initialized :
    OfValueWith.C t (Value.StructTuple "spl_token_interface::state::AccountState::Initialized" [] [] []) :=
  {
    value := Initialized;
    eq := eq_refl;
  }.

  Global Instance IsOfValue_Initialized :
    OfValue.C (Value.StructTuple "spl_token_interface::state::AccountState::Initialized" [] [] []) :=
  {
    value := Initialized;
    eq := eq_refl;
  }.

  Global Instance IsOfValueWith_Frozen :
    OfValueWith.C t (Value.StructTuple "spl_token_interface::state::AccountState::Frozen" [] [] []) :=
  {
    value := Frozen;
    eq := eq_refl;
  }.

  Global Instance IsOfValue_Frozen :
    OfValue.C (Value.StructTuple "spl_token_interface::state::AccountState::Frozen" [] [] []) :=
  {
    value := Frozen;
    eq := eq_refl;
  }.

  Module SubPointer.
  End SubPointer.
End AccountState.

(*
  pub struct Mint {
      pub mint_authority: COption<Pubkey>,
      pub supply: u64,
      pub decimals: u8,
      pub is_initialized: bool,
      pub freeze_authority: COption<Pubkey>,
  }
*)
Module Mint.
  Record t : Set := {
    mint_authority : COption.t Address.t;
    supply : u64;
    decimals : u8;
    is_initialized : bool;
    freeze_authority : COption.t Address.t;
  }.

  Global Instance IsLink : Link t := {
    Φ := Ty.path "spl_token_interface::state::Mint";
    φ x :=
      Value.StructRecord "spl_token_interface::state::Mint" [] [] [
        ("decimals", φ x.(decimals));
        ("freeze_authority", φ x.(freeze_authority));
        ("is_initialized", φ x.(is_initialized));
        ("mint_authority", φ x.(mint_authority));
        ("supply", φ x.(supply))
      ];
  }.

  Global Instance IsOfTy : OfTy.C (Ty.path "spl_token_interface::state::Mint") :=
  {
    A := t;
    eq := eq_refl;
  }.

  Global Instance IsOfValueWith
      (decimals' : Value.t) {H_decimals : OfValueWith.C (u8) decimals'}
      (freeze_authority' : Value.t) {H_freeze_authority : OfValueWith.C (COption.t Address.t) freeze_authority'}
      (is_initialized' : Value.t) {H_is_initialized : OfValueWith.C (bool) is_initialized'}
      (mint_authority' : Value.t) {H_mint_authority : OfValueWith.C (COption.t Address.t) mint_authority'}
      (supply' : Value.t) {H_supply : OfValueWith.C (u64) supply'}
      :
    OfValueWith.C t (Value.StructRecord "spl_token_interface::state::Mint" [] [] [
      ("decimals", decimals');
      ("freeze_authority", freeze_authority');
      ("is_initialized", is_initialized');
      ("mint_authority", mint_authority');
      ("supply", supply')
    ]) :=
  {
    value := Build_t
      H_mint_authority.(OfValueWith.value)
      H_supply.(OfValueWith.value)
      H_decimals.(OfValueWith.value)
      H_is_initialized.(OfValueWith.value)
      H_freeze_authority.(OfValueWith.value)
;
    eq := ltac:(sauto lq: on);
  }.

  Global Instance IsOfValue
      (decimals' : Value.t) {H_decimals : OfValueWith.C (u8) decimals'}
      (freeze_authority' : Value.t) {H_freeze_authority : OfValueWith.C (COption.t Address.t) freeze_authority'}
      (is_initialized' : Value.t) {H_is_initialized : OfValueWith.C (bool) is_initialized'}
      (mint_authority' : Value.t) {H_mint_authority : OfValueWith.C (COption.t Address.t) mint_authority'}
      (supply' : Value.t) {H_supply : OfValueWith.C (u64) supply'}
      :
    OfValue.C (Value.StructRecord "spl_token_interface::state::Mint" [] [] [
      ("decimals", decimals');
      ("freeze_authority", freeze_authority');
      ("is_initialized", is_initialized');
      ("mint_authority", mint_authority');
      ("supply", supply')
    ]) :=
  {
    value := Build_t
      H_mint_authority.(OfValueWith.value)
      H_supply.(OfValueWith.value)
      H_decimals.(OfValueWith.value)
      H_is_initialized.(OfValueWith.value)
      H_freeze_authority.(OfValueWith.value)
;
    eq := ltac:(sauto lq: on);
  }.

  Module SubPointer.
    Definition get_mint_authority : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Mint" "mint_authority") :=
    {|
      SubPointer.Runner.projection x := Some x.(mint_authority);
      SubPointer.Runner.injection x y := Some (x <| mint_authority := y |>);
    |}.

    Lemma get_mint_authority_is_valid :
      SubPointer.Runner.Valid.t get_mint_authority.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_mint_authority_is_valid : run_sub_pointer.

    Definition get_supply : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Mint" "supply") :=
    {|
      SubPointer.Runner.projection x := Some x.(supply);
      SubPointer.Runner.injection x y := Some (x <| supply := y |>);
    |}.

    Lemma get_supply_is_valid :
      SubPointer.Runner.Valid.t get_supply.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_supply_is_valid : run_sub_pointer.

    Definition get_decimals : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Mint" "decimals") :=
    {|
      SubPointer.Runner.projection x := Some x.(decimals);
      SubPointer.Runner.injection x y := Some (x <| decimals := y |>);
    |}.

    Lemma get_decimals_is_valid :
      SubPointer.Runner.Valid.t get_decimals.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_decimals_is_valid : run_sub_pointer.

    Definition get_is_initialized : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Mint" "is_initialized") :=
    {|
      SubPointer.Runner.projection x := Some x.(is_initialized);
      SubPointer.Runner.injection x y := Some (x <| is_initialized := y |>);
    |}.

    Lemma get_is_initialized_is_valid :
      SubPointer.Runner.Valid.t get_is_initialized.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_is_initialized_is_valid : run_sub_pointer.

    Definition get_freeze_authority : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Mint" "freeze_authority") :=
    {|
      SubPointer.Runner.projection x := Some x.(freeze_authority);
      SubPointer.Runner.injection x y := Some (x <| freeze_authority := y |>);
    |}.

    Lemma get_freeze_authority_is_valid :
      SubPointer.Runner.Valid.t get_freeze_authority.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_freeze_authority_is_valid : run_sub_pointer.
  End SubPointer.
End Mint.

(*
  pub struct Account {
      pub mint: Pubkey,
      pub owner: Pubkey,
      pub amount: u64,
      pub delegate: COption<Pubkey>,
      pub state: AccountState,
      pub is_native: COption<u64>,
      pub delegated_amount: u64,
      pub close_authority: COption<Pubkey>,
  }
*)
Module Account.
  Record t : Set := {
    mint : Address.t;
    owner : Address.t;
    amount : u64;
    delegate : COption.t Address.t;
    state : AccountState.t;
    is_native : COption.t u64;
    delegated_amount : u64;
    close_authority : COption.t Address.t;
  }.

  Global Instance IsLink : Link t := {
    Φ := Ty.path "spl_token_interface::state::Account";
    φ x :=
      Value.StructRecord "spl_token_interface::state::Account" [] [] [
        ("amount", φ x.(amount));
        ("close_authority", φ x.(close_authority));
        ("delegate", φ x.(delegate));
        ("delegated_amount", φ x.(delegated_amount));
        ("is_native", φ x.(is_native));
        ("mint", φ x.(mint));
        ("owner", φ x.(owner));
        ("state", φ x.(state))
      ];
  }.

  Global Instance IsOfTy : OfTy.C (Ty.path "spl_token_interface::state::Account") :=
  {
    A := t;
    eq := eq_refl;
  }.

  Global Instance IsOfValueWith
      (amount' : Value.t) {H_amount : OfValueWith.C (u64) amount'}
      (close_authority' : Value.t) {H_close_authority : OfValueWith.C (COption.t Address.t) close_authority'}
      (delegate' : Value.t) {H_delegate : OfValueWith.C (COption.t Address.t) delegate'}
      (delegated_amount' : Value.t) {H_delegated_amount : OfValueWith.C (u64) delegated_amount'}
      (is_native' : Value.t) {H_is_native : OfValueWith.C (COption.t u64) is_native'}
      (mint' : Value.t) {H_mint : OfValueWith.C (Address.t) mint'}
      (owner' : Value.t) {H_owner : OfValueWith.C (Address.t) owner'}
      (state' : Value.t) {H_state : OfValueWith.C (AccountState.t) state'}
      :
    OfValueWith.C t (Value.StructRecord "spl_token_interface::state::Account" [] [] [
      ("amount", amount');
      ("close_authority", close_authority');
      ("delegate", delegate');
      ("delegated_amount", delegated_amount');
      ("is_native", is_native');
      ("mint", mint');
      ("owner", owner');
      ("state", state')
    ]) :=
  {
    value := Build_t
      H_mint.(OfValueWith.value)
      H_owner.(OfValueWith.value)
      H_amount.(OfValueWith.value)
      H_delegate.(OfValueWith.value)
      H_state.(OfValueWith.value)
      H_is_native.(OfValueWith.value)
      H_delegated_amount.(OfValueWith.value)
      H_close_authority.(OfValueWith.value)
;
    eq := ltac:(sauto lq: on);
  }.

  Global Instance IsOfValue
      (amount' : Value.t) {H_amount : OfValueWith.C (u64) amount'}
      (close_authority' : Value.t) {H_close_authority : OfValueWith.C (COption.t Address.t) close_authority'}
      (delegate' : Value.t) {H_delegate : OfValueWith.C (COption.t Address.t) delegate'}
      (delegated_amount' : Value.t) {H_delegated_amount : OfValueWith.C (u64) delegated_amount'}
      (is_native' : Value.t) {H_is_native : OfValueWith.C (COption.t u64) is_native'}
      (mint' : Value.t) {H_mint : OfValueWith.C (Address.t) mint'}
      (owner' : Value.t) {H_owner : OfValueWith.C (Address.t) owner'}
      (state' : Value.t) {H_state : OfValueWith.C (AccountState.t) state'}
      :
    OfValue.C (Value.StructRecord "spl_token_interface::state::Account" [] [] [
      ("amount", amount');
      ("close_authority", close_authority');
      ("delegate", delegate');
      ("delegated_amount", delegated_amount');
      ("is_native", is_native');
      ("mint", mint');
      ("owner", owner');
      ("state", state')
    ]) :=
  {
    value := Build_t
      H_mint.(OfValueWith.value)
      H_owner.(OfValueWith.value)
      H_amount.(OfValueWith.value)
      H_delegate.(OfValueWith.value)
      H_state.(OfValueWith.value)
      H_is_native.(OfValueWith.value)
      H_delegated_amount.(OfValueWith.value)
      H_close_authority.(OfValueWith.value)
;
    eq := ltac:(sauto lq: on);
  }.

  Module SubPointer.
    Definition get_mint : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Account" "mint") :=
    {|
      SubPointer.Runner.projection x := Some x.(mint);
      SubPointer.Runner.injection x y := Some (x <| mint := y |>);
    |}.

    Lemma get_mint_is_valid :
      SubPointer.Runner.Valid.t get_mint.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_mint_is_valid : run_sub_pointer.

    Definition get_owner : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Account" "owner") :=
    {|
      SubPointer.Runner.projection x := Some x.(owner);
      SubPointer.Runner.injection x y := Some (x <| owner := y |>);
    |}.

    Lemma get_owner_is_valid :
      SubPointer.Runner.Valid.t get_owner.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_owner_is_valid : run_sub_pointer.

    Definition get_amount : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Account" "amount") :=
    {|
      SubPointer.Runner.projection x := Some x.(amount);
      SubPointer.Runner.injection x y := Some (x <| amount := y |>);
    |}.

    Lemma get_amount_is_valid :
      SubPointer.Runner.Valid.t get_amount.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_amount_is_valid : run_sub_pointer.

    Definition get_delegate : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Account" "delegate") :=
    {|
      SubPointer.Runner.projection x := Some x.(delegate);
      SubPointer.Runner.injection x y := Some (x <| delegate := y |>);
    |}.

    Lemma get_delegate_is_valid :
      SubPointer.Runner.Valid.t get_delegate.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_delegate_is_valid : run_sub_pointer.

    Definition get_state : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Account" "state") :=
    {|
      SubPointer.Runner.projection x := Some x.(state);
      SubPointer.Runner.injection x y := Some (x <| state := y |>);
    |}.

    Lemma get_state_is_valid :
      SubPointer.Runner.Valid.t get_state.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_state_is_valid : run_sub_pointer.

    Definition get_is_native : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Account" "is_native") :=
    {|
      SubPointer.Runner.projection x := Some x.(is_native);
      SubPointer.Runner.injection x y := Some (x <| is_native := y |>);
    |}.

    Lemma get_is_native_is_valid :
      SubPointer.Runner.Valid.t get_is_native.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_is_native_is_valid : run_sub_pointer.

    Definition get_delegated_amount : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Account" "delegated_amount") :=
    {|
      SubPointer.Runner.projection x := Some x.(delegated_amount);
      SubPointer.Runner.injection x y := Some (x <| delegated_amount := y |>);
    |}.

    Lemma get_delegated_amount_is_valid :
      SubPointer.Runner.Valid.t get_delegated_amount.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_delegated_amount_is_valid : run_sub_pointer.

    Definition get_close_authority : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "spl_token_interface::state::Account" "close_authority") :=
    {|
      SubPointer.Runner.projection x := Some x.(close_authority);
      SubPointer.Runner.injection x y := Some (x <| close_authority := y |>);
    |}.

    Lemma get_close_authority_is_valid :
      SubPointer.Runner.Valid.t get_close_authority.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_close_authority_is_valid : run_sub_pointer.
  End SubPointer.
End Account.

(* impl Account *)
Module Impl_Account.
  Definition Self : Set := Account.t.

  (* pub fn is_frozen(&self) -> bool *)
  Instance run_is_frozen
      (self : '& Self) :
    Run.Trait state.Impl_spl_token_interface_state_Account.is_frozen [] [] [φ self]
      bool.
  Proof.
    constructor.
    run_symbolic.
  Admitted.
  Global Opaque run_is_frozen.

  (* pub fn is_native(&self) -> bool *)
  Instance run_is_native
      (self : '& Self) :
    Run.Trait state.Impl_spl_token_interface_state_Account.is_native [] [] [φ self]
      bool.
  Proof.
    constructor.
    run_symbolic.
  Admitted.
  Global Opaque run_is_native.
End Impl_Account.
Export (hints) Impl_Account.

(* impl Pack for Mint *)
Module Impl_Pack_for_Mint.
  Instance run : Pack.Run Mint.t.
  Admitted.
End Impl_Pack_for_Mint.
Export (hints) Impl_Pack_for_Mint.

(* impl Pack for Account *)
Module Impl_Pack_for_Account.
  Instance run : Pack.Run Account.t.
  Admitted.
End Impl_Pack_for_Account.
Export (hints) Impl_Pack_for_Account.
