(* Generated by Jinja from revm/revm_interpreter/interpreter/links/stack.v.jinja2 - DO NOT EDIT *)
Require Import RocqOfRust.RocqOfRust.
Require Import RocqOfRust.links.M.
Require Import alloc.links.alloc.
Require Import alloc.vec.links.mod.
Require Import alloy_primitives.links.aliases.
Require Import core.fmt.links.mod.
Require Import core.fmt.links.rt.
Require Import core.iter.traits.links.collect.
Require Import core.links.array.
Require Import core.links.hint.
Require Import core.links.option.
Require Import core.links.panicking.
Require Import core.links.result.
Require Import core.slice.links.index.
Require Import core.slice.links.iter.
Require Import core.slice.links.mod.
Require Import revm.revm_interpreter.interpreter.stack.
Require Import revm.revm_interpreter.links.instruction_result.
Require Import ruint.links.lib.

(*
  pub struct Stack {
      data: Vec<U256>,
  }
*)
Module Stack.
  Record t : Set := {
    data : Vec.t aliases.U256.t Global.t;
  }.

  Instance IsLink : Link t := {
    Φ := Ty.path "revm_interpreter::interpreter::stack::Stack";
    φ x :=
      Value.StructRecord "revm_interpreter::interpreter::stack::Stack" [
        ("data", φ x.(data))
      ];
  }.

  Instance IsOfTy : OfTy.C (Ty.path "revm_interpreter::interpreter::stack::Stack") :=
  {
    A := t;
    eq := eq_refl;
  }.

  Instance IsOfValueWith
      (data' : Value.t) {H_data : OfValueWith.C (Vec.t aliases.U256.t Global.t) data'}
      :
    OfValueWith.C t (Value.StructRecord "revm_interpreter::interpreter::stack::Stack" [
      ("data", data')
    ]) :=
  {
    value := Build_t
      H_data.(OfValueWith.value)
;
    eq := ltac:(sauto lq: on);
  }.

  Instance IsOfValue
      (data' : Value.t) {H_data : OfValueWith.C (Vec.t aliases.U256.t Global.t) data'}
      :
    OfValue.C (Value.StructRecord "revm_interpreter::interpreter::stack::Stack" [
      ("data", data')
    ]) :=
  {
    value := Build_t
      H_data.(OfValueWith.value)
;
    eq := ltac:(sauto lq: on);
  }.

  Module SubPointer.
    Definition get_data : SubPointer.Runner.t t
      (Pointer.Index.StructRecord "revm_interpreter::interpreter::stack::Stack" "data") :=
    {|
      SubPointer.Runner.projection x := Some x.(data);
      SubPointer.Runner.injection x y := Some (x <| data := y |>);
    |}.

    Lemma get_data_is_valid :
      SubPointer.Runner.Valid.t get_data.
    Proof.
      now constructor.
    Qed.
    Smpl Add apply get_data_is_valid : run_sub_pointer.
  End SubPointer.
End Stack.
Export (hints) Stack.

Instance run_STACK_LIMIT :
  Run.Trait
    interpreter.stack.value_STACK_LIMIT [] [] []
    ('* usize).
Proof.
  constructor.
  run_symbolic.
Defined.
Global Opaque run_STACK_LIMIT.

Module Impl_Stack.
  Definition Self : Set :=
    Stack.t.

  (* pub fn new() -> Self *)
  Instance run_self :
    Run.Trait interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.new [] [] [] Self.
  Proof.
    constructor.
    run_symbolic.
  Defined.
  Global Opaque run_self.

  (* pub fn len(&self) -> usize *)
  Instance run_len (self : '& Self) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.len [] [] [φ self]
      usize.
  Proof.
    constructor.
    run_symbolic.
  Defined.
  Global Opaque run_len.

  (* pub fn is_empty(&self) -> bool *)
  Instance run_is_empty (self : '& Self) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.is_empty [] [] [φ self]
      bool.
  Proof.
    constructor.
    run_symbolic.
  Defined.
  Global Opaque run_is_empty.

  (* pub fn data(&self) -> &Vec<U256> *)
  Instance run_data (self : '& Self) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.data [] [] [φ self]
      ('& (Vec.t aliases.U256.t Global.t)).
  Proof.
    constructor.
    run_symbolic.
  Defined.
  Global Opaque run_data.

  (* pub fn data_mut(&mut self) -> &mut Vec<U256> *)
  Instance run_data_mut (self : '&mut Self) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.data_mut [] [] [φ self]
      ('&mut (Vec.t aliases.U256.t Global.t)).
  Proof.
    constructor.
    run_symbolic.
  Defined.
  Global Opaque run_data_mut.

  (* pub fn into_data(self) -> Vec<U256> *)
  Instance run_into_data (self : Self) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.into_data [] [] [φ self]
      (Vec.t aliases.U256.t Global.t).
  Proof.
    constructor.
    run_symbolic.
  Defined.
  Global Opaque run_into_data.

  (* pub fn pop(&mut self) -> Result<U256, InstructionResult> *)
  Instance run_pop (self : '&mut Self) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.pop [] [] [φ self]
      (Result.t aliases.U256.t InstructionResult.t).
  Proof.
    constructor.
    run_symbolic.
  Defined.
  Global Opaque run_pop.

  (* pub unsafe fn pop_unsafe(&mut self) -> U256 *)
  Instance run_pop_unsafe (self : '&mut Self) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.pop_unsafe [] [] [φ self]
      aliases.U256.t.
  Proof.
    constructor.
    run_symbolic.
  Defined.
  Global Opaque run_pop_unsafe.

  (* pub unsafe fn top_unsafe(&mut self) -> &mut U256 *)
  Instance run_top_unsafe (self : '&mut Self) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.top_unsafe [] [] [φ self]
      ('&mut aliases.U256.t).
  Proof.
    constructor.
    destruct (Impl_DerefMut_for_Vec.run aliases.U256.t Global.t).
    run_symbolic.
  Defined.
  Global Opaque run_top_unsafe.

  (* pub unsafe fn popn<const N: usize>(&mut self) -> [U256; N] *)
  Instance run_popn (N : usize) (self : '&mut Self) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.popn [φ N] [] [φ self]
      (array.t aliases.U256.t N).
  Proof.
    constructor.
    (* destruct (Impl_IntoIterator_for_Iterator_I.run (IterMut.t aliases.U256.t) aliases.U256.t). *)
    run_symbolic.
  Admitted.
  Global Opaque run_popn.

  (* pub unsafe fn popn_top<const POPN: usize>(&mut self) -> ([U256; POPN], &mut U256) *)
  Instance run_popn_top (self : '&mut Self) (POPN : usize) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.popn_top [φ POPN] [] [φ self]
      (array.t aliases.U256.t POPN * '&mut aliases.U256.t).
  Proof.
    constructor.
    run_symbolic.
  Defined.
  Global Opaque run_popn_top.

  (* pub fn push(&mut self, value: U256) -> bool *)
  Instance run_push (self : '&mut Self) (value : aliases.U256.t) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.push [] [] [φ self; φ value]
      bool.
  Proof.
    constructor.
    run_symbolic.
  Defined.
  Global Opaque run_push.

  (* pub fn peek(&self, no_from_top: usize) -> Result<U256, InstructionResult> *)
  Instance run_peek (self : '& Self) (no_from_top : usize) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.peek
        [] [] [φ self; φ no_from_top]
      (Result.t aliases.U256.t InstructionResult.t).
  Proof.
    constructor.
    destruct (Impl_Index_for_Vec_T_A.run aliases.U256.t usize Global.t aliases.U256.t).
    run_symbolic.
  Admitted.
  Global Opaque run_peek.

  (* pub fn dup(&mut self, n: usize) -> bool *)
  Instance run_dup (self : '&mut Self) (n : usize) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.dup [] [] [φ self; φ n]
      bool.
  Proof.
    constructor.
    run_symbolic.
  Admitted.
  Global Opaque run_dup.

  (* pub fn exchange(&mut self, n: usize, m: usize) -> bool *)
  Instance run_exchange (self : '&mut Self) (n m : usize) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.exchange
        [] [] [φ self; φ n; φ m]
      bool.
  Proof.
    constructor.
    run_symbolic.
  Admitted.
  Global Opaque run_exchange.

  (* pub fn swap(&mut self, n: usize) -> bool *)
  Instance run_swap (self : '&mut Self) (n : usize) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.swap [] [] [φ self; φ n]
      bool.
  Proof.
    constructor.
    run_symbolic.
  Defined.
  Global Opaque run_swap.

  (* pub fn push_slice(&mut self, slice: &[u8]) -> Result<(), InstructionResult> *)
  Instance run_push_slice
      (self : '&mut Self)
      (slice : '& (list u8)) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.push_slice
        [] [] [φ self; φ slice]
      (Result.t unit InstructionResult.t).
  Proof.
    constructor.
  Admitted.
  Global Opaque run_push_slice.

  (* pub fn set(&mut self, no_from_top: usize, val: U256) -> Result<(), InstructionResult> *)
  Instance run_set
      (self : '&mut Self)
      (no_from_top : usize)
      (val : aliases.U256.t) :
    Run.Trait
      interpreter.stack.Impl_revm_interpreter_interpreter_stack_Stack.set
        [] [] [φ self; φ no_from_top; φ val]
      (Result.t unit InstructionResult.t).
  Proof.
    constructor.
    run_symbolic.
  Admitted.
  Global Opaque run_set.
End Impl_Stack.
Export (hints) Impl_Stack.
