(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module try_commit.
  (* Trait *)
  (* Empty module 'TryDatabaseCommit' *)
  
  Module Impl_revm_database_interface_try_commit_TryDatabaseCommit_where_revm_database_interface_DatabaseCommit_Db_for_Db.
    Definition Self (Db : Ty.t) : Ty.t := Db.
    
    (*     type Error = Infallible; *)
    Definition _Error (Db : Ty.t) : Ty.t := Ty.path "core::convert::Infallible".
    
    (*
        fn try_commit(&mut self, changes: HashMap<Address, Account>) -> Result<(), Self::Error> {
            self.commit(changes);
            Ok(())
        }
    *)
    Definition try_commit (Db : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      let Self : Ty.t := Self Db in
      match ε, τ, α with
      | [], [], [ self; changes ] =>
        ltac:(M.monadic
          (let self := M.alloc (| Ty.apply (Ty.path "&mut") [] [ Db ], self |) in
          let changes :=
            M.alloc (|
              Ty.apply
                (Ty.path "std::collections::hash::map::HashMap")
                []
                [
                  Ty.path "alloy_primitives::bits::address::Address";
                  Ty.path "revm_state::Account";
                  Ty.path "std::hash::random::RandomState"
                ],
              changes
            |) in
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_trait_method (|
                  "revm_database_interface::DatabaseCommit",
                  Db,
                  [],
                  [],
                  "commit",
                  [],
                  []
                |),
                [
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |);
                  M.read (| changes |)
                ]
              |) in
            M.alloc (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [ Ty.tuple []; Ty.path "core::convert::Infallible" ],
              Value.StructTuple
                "core::result::Result::Ok"
                []
                [ Ty.tuple []; Ty.path "core::convert::Infallible" ]
                [ Value.Tuple [] ]
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      forall (Db : Ty.t),
      M.IsTraitInstance
        "revm_database_interface::try_commit::TryDatabaseCommit"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        (Self Db)
        (* Instance *)
        [
          ("Error", InstanceField.Ty (_Error Db));
          ("try_commit", InstanceField.Method (try_commit Db))
        ].
  End Impl_revm_database_interface_try_commit_TryDatabaseCommit_where_revm_database_interface_DatabaseCommit_Db_for_Db.
  
  (* StructTuple
    {
      name := "ArcUpgradeError";
      const_params := [];
      ty_params := [];
      fields := [];
    } *)
  
  Module Impl_core_fmt_Debug_for_revm_database_interface_try_commit_ArcUpgradeError.
    Definition Self : Ty.t := Ty.path "revm_database_interface::try_commit::ArcUpgradeError".
    
    (* Debug *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_database_interface::try_commit::ArcUpgradeError" ],
              self
            |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.call_closure (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            M.get_associated_function (| Ty.path "core::fmt::Formatter", "write_str", [], [] |),
            [
              M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "ArcUpgradeError" |) |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Debug"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Debug_for_revm_database_interface_try_commit_ArcUpgradeError.
  
  Module Impl_core_clone_TrivialClone_for_revm_database_interface_try_commit_ArcUpgradeError.
    Definition Self : Ty.t := Ty.path "revm_database_interface::try_commit::ArcUpgradeError".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::TrivialClone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_clone_TrivialClone_for_revm_database_interface_try_commit_ArcUpgradeError.
  
  Module Impl_core_clone_Clone_for_revm_database_interface_try_commit_ArcUpgradeError.
    Definition Self : Ty.t := Ty.path "revm_database_interface::try_commit::ArcUpgradeError".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_database_interface::try_commit::ArcUpgradeError" ],
              self
            |) in
          M.read (| M.deref (| M.read (| self |) |) |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_revm_database_interface_try_commit_ArcUpgradeError.
  
  Module Impl_core_marker_Copy_for_revm_database_interface_try_commit_ArcUpgradeError.
    Definition Self : Ty.t := Ty.path "revm_database_interface::try_commit::ArcUpgradeError".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::Copy"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_Copy_for_revm_database_interface_try_commit_ArcUpgradeError.
  
  Module Impl_core_marker_StructuralPartialEq_for_revm_database_interface_try_commit_ArcUpgradeError.
    Definition Self : Ty.t := Ty.path "revm_database_interface::try_commit::ArcUpgradeError".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::StructuralPartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_StructuralPartialEq_for_revm_database_interface_try_commit_ArcUpgradeError.
  
  Module Impl_core_cmp_PartialEq_revm_database_interface_try_commit_ArcUpgradeError_for_revm_database_interface_try_commit_ArcUpgradeError.
    Definition Self : Ty.t := Ty.path "revm_database_interface::try_commit::ArcUpgradeError".
    
    (* PartialEq *)
    Definition eq (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; other ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_database_interface::try_commit::ArcUpgradeError" ],
              self
            |) in
          let other :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_database_interface::try_commit::ArcUpgradeError" ],
              other
            |) in
          Value.Bool true))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::PartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *)
        [ Ty.path "revm_database_interface::try_commit::ArcUpgradeError" ]
        Self
        (* Instance *) [ ("eq", InstanceField.Method eq) ].
  End Impl_core_cmp_PartialEq_revm_database_interface_try_commit_ArcUpgradeError_for_revm_database_interface_try_commit_ArcUpgradeError.
  
  Module Impl_core_cmp_Eq_for_revm_database_interface_try_commit_ArcUpgradeError.
    Definition Self : Ty.t := Ty.path "revm_database_interface::try_commit::ArcUpgradeError".
    
    (* Eq *)
    Definition assert_receiver_is_total_eq
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_database_interface::try_commit::ArcUpgradeError" ],
              self
            |) in
          Value.Tuple []))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::Eq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *)
        [ ("assert_receiver_is_total_eq", InstanceField.Method assert_receiver_is_total_eq) ].
  End Impl_core_cmp_Eq_for_revm_database_interface_try_commit_ArcUpgradeError.
  
  Module Impl_core_fmt_Display_for_revm_database_interface_try_commit_ArcUpgradeError.
    Definition Self : Ty.t := Ty.path "revm_database_interface::try_commit::ArcUpgradeError".
    
    (*
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            write!(f, "Arc reference is not unique, cannot mutate")
        }
    *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.path "revm_database_interface::try_commit::ArcUpgradeError" ],
              self
            |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.call_closure (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            M.get_associated_function (| Ty.path "core::fmt::Formatter", "write_fmt", [], [] |),
            [
              M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
              M.call_closure (|
                Ty.path "core::fmt::Arguments",
                M.get_associated_function (| Ty.path "core::fmt::Arguments", "from_str", [], [] |),
                [ mk_str (| "Arc reference is not unique, cannot mutate" |) ]
              |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Display"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Display_for_revm_database_interface_try_commit_ArcUpgradeError.
  
  Module Impl_core_error_Error_for_revm_database_interface_try_commit_ArcUpgradeError.
    Definition Self : Ty.t := Ty.path "revm_database_interface::try_commit::ArcUpgradeError".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::error::Error"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_error_Error_for_revm_database_interface_try_commit_ArcUpgradeError.
  
  Module Impl_revm_database_interface_try_commit_TryDatabaseCommit_where_revm_database_interface_DatabaseCommit_Db_for_alloc_sync_Arc_Db_alloc_alloc_Global.
    Definition Self (Db : Ty.t) : Ty.t :=
      Ty.apply (Ty.path "alloc::sync::Arc") [] [ Db; Ty.path "alloc::alloc::Global" ].
    
    (*     type Error = ArcUpgradeError; *)
    Definition _Error (Db : Ty.t) : Ty.t :=
      Ty.path "revm_database_interface::try_commit::ArcUpgradeError".
    
    (*
        fn try_commit(&mut self, changes: HashMap<Address, Account>) -> Result<(), Self::Error> {
            Arc::get_mut(self)
                .map(|db| db.commit(changes))
                .ok_or(ArcUpgradeError)
        }
    *)
    Definition try_commit (Db : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      let Self : Ty.t := Self Db in
      match ε, τ, α with
      | [], [], [ self; changes ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "alloc::sync::Arc") [] [ Db; Ty.path "alloc::alloc::Global" ] ],
              self
            |) in
          let changes :=
            M.alloc (|
              Ty.apply
                (Ty.path "std::collections::hash::map::HashMap")
                []
                [
                  Ty.path "alloy_primitives::bits::address::Address";
                  Ty.path "revm_state::Account";
                  Ty.path "std::hash::random::RandomState"
                ],
              changes
            |) in
          M.call_closure (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "revm_database_interface::try_commit::ArcUpgradeError" ],
            M.get_associated_function (|
              Ty.apply (Ty.path "core::option::Option") [] [ Ty.tuple [] ],
              "ok_or",
              [],
              [ Ty.path "revm_database_interface::try_commit::ArcUpgradeError" ]
            |),
            [
              M.call_closure (|
                Ty.apply (Ty.path "core::option::Option") [] [ Ty.tuple [] ],
                M.get_associated_function (|
                  Ty.apply
                    (Ty.path "core::option::Option")
                    []
                    [ Ty.apply (Ty.path "&mut") [] [ Db ] ],
                  "map",
                  [],
                  [ Ty.tuple []; Ty.function [ Ty.apply (Ty.path "&mut") [] [ Db ] ] (Ty.tuple []) ]
                |),
                [
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::option::Option")
                      []
                      [ Ty.apply (Ty.path "&mut") [] [ Db ] ],
                    M.get_associated_function (|
                      Ty.apply
                        (Ty.path "alloc::sync::Arc")
                        []
                        [ Db; Ty.path "alloc::alloc::Global" ],
                      "get_mut",
                      [],
                      []
                    |),
                    [ M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |) ]
                  |);
                  M.closure
                    (fun γ =>
                      ltac:(M.monadic
                        match γ with
                        | [ α0 ] =>
                          ltac:(M.monadic
                            (M.match_operator (|
                              Ty.tuple [],
                              M.alloc (| Ty.apply (Ty.path "&mut") [] [ Db ], α0 |),
                              [
                                fun γ =>
                                  ltac:(M.monadic
                                    (let db :=
                                      M.copy (| Ty.apply (Ty.path "&mut") [] [ Db ], γ |) in
                                    M.call_closure (|
                                      Ty.tuple [],
                                      M.get_trait_method (|
                                        "revm_database_interface::DatabaseCommit",
                                        Db,
                                        [],
                                        [],
                                        "commit",
                                        [],
                                        []
                                      |),
                                      [
                                        M.borrow (|
                                          Pointer.Kind.MutRef,
                                          M.deref (| M.read (| db |) |)
                                        |);
                                        M.read (| changes |)
                                      ]
                                    |)))
                              ]
                            |)))
                        | _ => M.impossible "wrong number of arguments"
                        end))
                ]
              |);
              Value.StructTuple "revm_database_interface::try_commit::ArcUpgradeError" [] [] []
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      forall (Db : Ty.t),
      M.IsTraitInstance
        "revm_database_interface::try_commit::TryDatabaseCommit"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        (Self Db)
        (* Instance *)
        [
          ("Error", InstanceField.Ty (_Error Db));
          ("try_commit", InstanceField.Method (try_commit Db))
        ].
  End Impl_revm_database_interface_try_commit_TryDatabaseCommit_where_revm_database_interface_DatabaseCommit_Db_for_alloc_sync_Arc_Db_alloc_alloc_Global.
End try_commit.
