(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

(*
fn foo<A>(o: Option<A>) {
    match o {
        Some(_a) => println!("some"),
        None => println!("nothing"),
    }
}
*)
Definition foo (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
  match ε, τ, α with
  | [], [ A ], [ o ] =>
    ltac:(M.monadic
      (let o := M.alloc (| Ty.apply (Ty.path "core::option::Option") [] [ A ], o |) in
      M.match_operator (|
        Ty.tuple [],
        o,
        [
          fun γ =>
            ltac:(M.monadic
              (let γ0_0 :=
                M.SubPointer.get_struct_tuple_field (| γ, "core::option::Option::Some", 0 |) in
              let _a := M.copy (| A, γ0_0 |) in
              M.read (|
                let~ _ : Ty.tuple [] :=
                  M.call_closure (|
                    Ty.tuple [],
                    M.get_function (| "std::io::stdio::_print", [], [] |),
                    [
                      M.value_with_ty
                        (M.call_closure (|
                          Ty.path "core::fmt::Arguments",
                          M.get_associated_function (|
                            Ty.path "core::fmt::Arguments",
                            "new_const",
                            [ Value.Integer IntegerKind.Usize 1 ],
                            []
                          |),
                          [
                            M.value_with_ty
                              (M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.borrow (|
                                    Pointer.Kind.Ref,
                                    M.alloc (|
                                      Ty.apply
                                        (Ty.path "array")
                                        [ Value.Integer IntegerKind.Usize 1 ]
                                        [ Ty.apply (Ty.path "&") [] [ Ty.path "str" ] ],
                                      Value.Array [ mk_str (| "some
" |) ]
                                    |)
                                  |)
                                |)
                              |))
                              (Ty.apply
                                (Ty.path "&")
                                []
                                [
                                  Ty.apply
                                    (Ty.path "array")
                                    [ Value.Integer IntegerKind.Usize 1 ]
                                    [ Ty.apply (Ty.path "&") [] [ Ty.path "str" ] ]
                                ])
                          ]
                        |))
                        (Ty.path "core::fmt::Arguments")
                    ]
                  |) in
                M.alloc (| Ty.tuple [], Value.Tuple [] |)
              |)));
          fun γ =>
            ltac:(M.monadic
              (let _ := M.is_struct_tuple (| γ, "core::option::Option::None" |) in
              M.read (|
                let~ _ : Ty.tuple [] :=
                  M.call_closure (|
                    Ty.tuple [],
                    M.get_function (| "std::io::stdio::_print", [], [] |),
                    [
                      M.value_with_ty
                        (M.call_closure (|
                          Ty.path "core::fmt::Arguments",
                          M.get_associated_function (|
                            Ty.path "core::fmt::Arguments",
                            "new_const",
                            [ Value.Integer IntegerKind.Usize 1 ],
                            []
                          |),
                          [
                            M.value_with_ty
                              (M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.borrow (|
                                    Pointer.Kind.Ref,
                                    M.alloc (|
                                      Ty.apply
                                        (Ty.path "array")
                                        [ Value.Integer IntegerKind.Usize 1 ]
                                        [ Ty.apply (Ty.path "&") [] [ Ty.path "str" ] ],
                                      Value.Array [ mk_str (| "nothing
" |) ]
                                    |)
                                  |)
                                |)
                              |))
                              (Ty.apply
                                (Ty.path "&")
                                []
                                [
                                  Ty.apply
                                    (Ty.path "array")
                                    [ Value.Integer IntegerKind.Usize 1 ]
                                    [ Ty.apply (Ty.path "&") [] [ Ty.path "str" ] ]
                                ])
                          ]
                        |))
                        (Ty.path "core::fmt::Arguments")
                    ]
                  |) in
                M.alloc (| Ty.tuple [], Value.Tuple [] |)
              |)))
        ]
      |)))
  | _, _, _ => M.impossible "wrong number of arguments"
  end.

Global Instance Instance_IsFunction_foo : M.IsFunction.C "concurrent_tests::foo" foo.
Admitted.
Global Typeclasses Opaque foo.

Module tests.
  (*
      fn test_file() {
          // Opens the file ferris.txt or creates one if it doesn't exist.
          let mut file = OpenOptions::new()
              .append(true)
              .create(true)
              .open("ferris.txt")
              .expect("Failed to open ferris.txt");
  
          // Print "Ferris" 5 times.
          for _ in 0..5 {
              file.write_all("Ferris\n".as_bytes())
                  .expect("Could not write to ferris.txt");
          }
      }
  *)
  Definition test_file (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    match ε, τ, α with
    | [], [], [] =>
      ltac:(M.monadic
        (M.read (|
          let~ file : Ty.path "std::fs::File" :=
            M.call_closure (|
              Ty.path "std::fs::File",
              M.get_associated_function (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [ Ty.path "std::fs::File"; Ty.path "std::io::error::Error" ],
                "expect",
                [],
                []
              |),
              [
                M.value_with_ty
                  (M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.path "std::fs::File"; Ty.path "std::io::error::Error" ],
                    M.get_associated_function (|
                      Ty.path "std::fs::OpenOptions",
                      "open",
                      [],
                      [ Ty.apply (Ty.path "&") [] [ Ty.path "str" ] ]
                    |),
                    [
                      M.value_with_ty
                        (M.borrow (|
                          Pointer.Kind.Ref,
                          M.deref (|
                            M.call_closure (|
                              Ty.apply (Ty.path "&mut") [] [ Ty.path "std::fs::OpenOptions" ],
                              M.get_associated_function (|
                                Ty.path "std::fs::OpenOptions",
                                "create",
                                [],
                                []
                              |),
                              [
                                M.value_with_ty
                                  (M.borrow (|
                                    Pointer.Kind.MutRef,
                                    M.deref (|
                                      M.call_closure (|
                                        Ty.apply
                                          (Ty.path "&mut")
                                          []
                                          [ Ty.path "std::fs::OpenOptions" ],
                                        M.get_associated_function (|
                                          Ty.path "std::fs::OpenOptions",
                                          "append",
                                          [],
                                          []
                                        |),
                                        [
                                          M.value_with_ty
                                            (M.borrow (|
                                              Pointer.Kind.MutRef,
                                              M.alloc (|
                                                Ty.path "std::fs::OpenOptions",
                                                M.call_closure (|
                                                  Ty.path "std::fs::OpenOptions",
                                                  M.get_associated_function (|
                                                    Ty.path "std::fs::OpenOptions",
                                                    "new",
                                                    [],
                                                    []
                                                  |),
                                                  []
                                                |)
                                              |)
                                            |))
                                            (Ty.apply
                                              (Ty.path "&mut")
                                              []
                                              [ Ty.path "std::fs::OpenOptions" ]);
                                          M.value_with_ty (Value.Bool true) (Ty.path "bool")
                                        ]
                                      |)
                                    |)
                                  |))
                                  (Ty.apply (Ty.path "&mut") [] [ Ty.path "std::fs::OpenOptions" ]);
                                M.value_with_ty (Value.Bool true) (Ty.path "bool")
                              ]
                            |)
                          |)
                        |))
                        (Ty.apply (Ty.path "&") [] [ Ty.path "std::fs::OpenOptions" ]);
                      M.value_with_ty
                        (mk_str (| "ferris.txt" |))
                        (Ty.apply (Ty.path "&") [] [ Ty.path "str" ])
                    ]
                  |))
                  (Ty.apply
                    (Ty.path "core::result::Result")
                    []
                    [ Ty.path "std::fs::File"; Ty.path "std::io::error::Error" ]);
                M.value_with_ty
                  (M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (| mk_str (| "Failed to open ferris.txt" |) |)
                  |))
                  (Ty.apply (Ty.path "&") [] [ Ty.path "str" ])
              ]
            |) in
          M.use
            (M.alloc (|
              Ty.tuple [],
              M.match_operator (|
                Ty.tuple [],
                M.alloc (|
                  Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ],
                  M.call_closure (|
                    Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ],
                    M.get_trait_method (|
                      "core::iter::traits::collect::IntoIterator",
                      Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ],
                      [],
                      [],
                      "into_iter",
                      [],
                      []
                    |),
                    [
                      M.value_with_ty
                        (M.value_with_ty
                          (Value.mkStructRecord
                            "core::ops::range::Range"
                            [
                              ("start", Value.Integer IntegerKind.I32 0);
                              ("end_", Value.Integer IntegerKind.I32 5)
                            ])
                          (Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ]))
                        (Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ])
                    ]
                  |)
                |),
                [
                  fun γ =>
                    ltac:(M.monadic
                      (let~ iter :
                          Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ] :=
                        M.read (| γ |) in
                      M.read (|
                        M.loop (|
                          Ty.tuple [],
                          ltac:(M.monadic
                            (let~ _ : Ty.tuple [] :=
                              M.match_operator (|
                                Ty.tuple [],
                                M.alloc (|
                                  Ty.apply (Ty.path "core::option::Option") [] [ Ty.path "i32" ],
                                  M.call_closure (|
                                    Ty.apply (Ty.path "core::option::Option") [] [ Ty.path "i32" ],
                                    M.get_trait_method (|
                                      "core::iter::traits::iterator::Iterator",
                                      Ty.apply
                                        (Ty.path "core::ops::range::Range")
                                        []
                                        [ Ty.path "i32" ],
                                      [],
                                      [],
                                      "next",
                                      [],
                                      []
                                    |),
                                    [
                                      M.value_with_ty
                                        (M.borrow (|
                                          Pointer.Kind.MutRef,
                                          M.deref (| M.borrow (| Pointer.Kind.MutRef, iter |) |)
                                        |))
                                        (Ty.apply
                                          (Ty.path "&mut")
                                          []
                                          [
                                            Ty.apply
                                              (Ty.path "core::ops::range::Range")
                                              []
                                              [ Ty.path "i32" ]
                                          ])
                                    ]
                                  |)
                                |),
                                [
                                  fun γ =>
                                    ltac:(M.monadic
                                      (let _ :=
                                        M.is_struct_tuple (| γ, "core::option::Option::None" |) in
                                      M.never_to_any (| M.read (| M.break (||) |) |)));
                                  fun γ =>
                                    ltac:(M.monadic
                                      (let γ0_0 :=
                                        M.SubPointer.get_struct_tuple_field (|
                                          γ,
                                          "core::option::Option::Some",
                                          0
                                        |) in
                                      M.read (|
                                        let~ _ : Ty.tuple [] :=
                                          M.call_closure (|
                                            Ty.tuple [],
                                            M.get_associated_function (|
                                              Ty.apply
                                                (Ty.path "core::result::Result")
                                                []
                                                [ Ty.tuple []; Ty.path "std::io::error::Error" ],
                                              "expect",
                                              [],
                                              []
                                            |),
                                            [
                                              M.value_with_ty
                                                (M.call_closure (|
                                                  Ty.apply
                                                    (Ty.path "core::result::Result")
                                                    []
                                                    [ Ty.tuple []; Ty.path "std::io::error::Error"
                                                    ],
                                                  M.get_trait_method (|
                                                    "std::io::Write",
                                                    Ty.path "std::fs::File",
                                                    [],
                                                    [],
                                                    "write_all",
                                                    [],
                                                    []
                                                  |),
                                                  [
                                                    M.value_with_ty
                                                      (M.borrow (| Pointer.Kind.MutRef, file |))
                                                      (Ty.apply
                                                        (Ty.path "&mut")
                                                        []
                                                        [ Ty.path "std::fs::File" ]);
                                                    M.value_with_ty
                                                      (M.borrow (|
                                                        Pointer.Kind.Ref,
                                                        M.deref (|
                                                          M.call_closure (|
                                                            Ty.apply
                                                              (Ty.path "&")
                                                              []
                                                              [
                                                                Ty.apply
                                                                  (Ty.path "slice")
                                                                  []
                                                                  [ Ty.path "u8" ]
                                                              ],
                                                            M.get_associated_function (|
                                                              Ty.path "str",
                                                              "as_bytes",
                                                              [],
                                                              []
                                                            |),
                                                            [
                                                              M.value_with_ty
                                                                (M.borrow (|
                                                                  Pointer.Kind.Ref,
                                                                  M.deref (|
                                                                    mk_str (| "Ferris
" |)
                                                                  |)
                                                                |))
                                                                (Ty.apply
                                                                  (Ty.path "&")
                                                                  []
                                                                  [ Ty.path "str" ])
                                                            ]
                                                          |)
                                                        |)
                                                      |))
                                                      (Ty.apply
                                                        (Ty.path "&")
                                                        []
                                                        [
                                                          Ty.apply
                                                            (Ty.path "slice")
                                                            []
                                                            [ Ty.path "u8" ]
                                                        ])
                                                  ]
                                                |))
                                                (Ty.apply
                                                  (Ty.path "core::result::Result")
                                                  []
                                                  [ Ty.tuple []; Ty.path "std::io::error::Error" ]);
                                              M.value_with_ty
                                                (M.borrow (|
                                                  Pointer.Kind.Ref,
                                                  M.deref (|
                                                    mk_str (| "Could not write to ferris.txt" |)
                                                  |)
                                                |))
                                                (Ty.apply (Ty.path "&") [] [ Ty.path "str" ])
                                            ]
                                          |) in
                                        M.alloc (| Ty.tuple [], Value.Tuple [] |)
                                      |)))
                                ]
                              |) in
                            M.alloc (| Ty.tuple [], Value.Tuple [] |)))
                        |)
                      |)))
                ]
              |)
            |))
        |)))
    | _, _, _ => M.impossible "wrong number of arguments"
    end.
  
  Global Instance Instance_IsFunction_test_file :
    M.IsFunction.C "concurrent_tests::tests::test_file'1" test_file.
  Admitted.
  Global Typeclasses Opaque test_file.
  
  (*
      fn test_file_also() {
          // Opens the file ferris.txt or creates one if it doesn't exist.
          let mut file = OpenOptions::new()
              .append(true)
              .create(true)
              .open("ferris.txt")
              .expect("Failed to open ferris.txt");
  
          // Print "Corro" 5 times.
          for _ in 0..5 {
              file.write_all("Corro\n".as_bytes())
                  .expect("Could not write to ferris.txt");
          }
      }
  *)
  Definition test_file_also (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    match ε, τ, α with
    | [], [], [] =>
      ltac:(M.monadic
        (M.read (|
          let~ file : Ty.path "std::fs::File" :=
            M.call_closure (|
              Ty.path "std::fs::File",
              M.get_associated_function (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [ Ty.path "std::fs::File"; Ty.path "std::io::error::Error" ],
                "expect",
                [],
                []
              |),
              [
                M.value_with_ty
                  (M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.path "std::fs::File"; Ty.path "std::io::error::Error" ],
                    M.get_associated_function (|
                      Ty.path "std::fs::OpenOptions",
                      "open",
                      [],
                      [ Ty.apply (Ty.path "&") [] [ Ty.path "str" ] ]
                    |),
                    [
                      M.value_with_ty
                        (M.borrow (|
                          Pointer.Kind.Ref,
                          M.deref (|
                            M.call_closure (|
                              Ty.apply (Ty.path "&mut") [] [ Ty.path "std::fs::OpenOptions" ],
                              M.get_associated_function (|
                                Ty.path "std::fs::OpenOptions",
                                "create",
                                [],
                                []
                              |),
                              [
                                M.value_with_ty
                                  (M.borrow (|
                                    Pointer.Kind.MutRef,
                                    M.deref (|
                                      M.call_closure (|
                                        Ty.apply
                                          (Ty.path "&mut")
                                          []
                                          [ Ty.path "std::fs::OpenOptions" ],
                                        M.get_associated_function (|
                                          Ty.path "std::fs::OpenOptions",
                                          "append",
                                          [],
                                          []
                                        |),
                                        [
                                          M.value_with_ty
                                            (M.borrow (|
                                              Pointer.Kind.MutRef,
                                              M.alloc (|
                                                Ty.path "std::fs::OpenOptions",
                                                M.call_closure (|
                                                  Ty.path "std::fs::OpenOptions",
                                                  M.get_associated_function (|
                                                    Ty.path "std::fs::OpenOptions",
                                                    "new",
                                                    [],
                                                    []
                                                  |),
                                                  []
                                                |)
                                              |)
                                            |))
                                            (Ty.apply
                                              (Ty.path "&mut")
                                              []
                                              [ Ty.path "std::fs::OpenOptions" ]);
                                          M.value_with_ty (Value.Bool true) (Ty.path "bool")
                                        ]
                                      |)
                                    |)
                                  |))
                                  (Ty.apply (Ty.path "&mut") [] [ Ty.path "std::fs::OpenOptions" ]);
                                M.value_with_ty (Value.Bool true) (Ty.path "bool")
                              ]
                            |)
                          |)
                        |))
                        (Ty.apply (Ty.path "&") [] [ Ty.path "std::fs::OpenOptions" ]);
                      M.value_with_ty
                        (mk_str (| "ferris.txt" |))
                        (Ty.apply (Ty.path "&") [] [ Ty.path "str" ])
                    ]
                  |))
                  (Ty.apply
                    (Ty.path "core::result::Result")
                    []
                    [ Ty.path "std::fs::File"; Ty.path "std::io::error::Error" ]);
                M.value_with_ty
                  (M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (| mk_str (| "Failed to open ferris.txt" |) |)
                  |))
                  (Ty.apply (Ty.path "&") [] [ Ty.path "str" ])
              ]
            |) in
          M.use
            (M.alloc (|
              Ty.tuple [],
              M.match_operator (|
                Ty.tuple [],
                M.alloc (|
                  Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ],
                  M.call_closure (|
                    Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ],
                    M.get_trait_method (|
                      "core::iter::traits::collect::IntoIterator",
                      Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ],
                      [],
                      [],
                      "into_iter",
                      [],
                      []
                    |),
                    [
                      M.value_with_ty
                        (M.value_with_ty
                          (Value.mkStructRecord
                            "core::ops::range::Range"
                            [
                              ("start", Value.Integer IntegerKind.I32 0);
                              ("end_", Value.Integer IntegerKind.I32 5)
                            ])
                          (Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ]))
                        (Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ])
                    ]
                  |)
                |),
                [
                  fun γ =>
                    ltac:(M.monadic
                      (let~ iter :
                          Ty.apply (Ty.path "core::ops::range::Range") [] [ Ty.path "i32" ] :=
                        M.read (| γ |) in
                      M.read (|
                        M.loop (|
                          Ty.tuple [],
                          ltac:(M.monadic
                            (let~ _ : Ty.tuple [] :=
                              M.match_operator (|
                                Ty.tuple [],
                                M.alloc (|
                                  Ty.apply (Ty.path "core::option::Option") [] [ Ty.path "i32" ],
                                  M.call_closure (|
                                    Ty.apply (Ty.path "core::option::Option") [] [ Ty.path "i32" ],
                                    M.get_trait_method (|
                                      "core::iter::traits::iterator::Iterator",
                                      Ty.apply
                                        (Ty.path "core::ops::range::Range")
                                        []
                                        [ Ty.path "i32" ],
                                      [],
                                      [],
                                      "next",
                                      [],
                                      []
                                    |),
                                    [
                                      M.value_with_ty
                                        (M.borrow (|
                                          Pointer.Kind.MutRef,
                                          M.deref (| M.borrow (| Pointer.Kind.MutRef, iter |) |)
                                        |))
                                        (Ty.apply
                                          (Ty.path "&mut")
                                          []
                                          [
                                            Ty.apply
                                              (Ty.path "core::ops::range::Range")
                                              []
                                              [ Ty.path "i32" ]
                                          ])
                                    ]
                                  |)
                                |),
                                [
                                  fun γ =>
                                    ltac:(M.monadic
                                      (let _ :=
                                        M.is_struct_tuple (| γ, "core::option::Option::None" |) in
                                      M.never_to_any (| M.read (| M.break (||) |) |)));
                                  fun γ =>
                                    ltac:(M.monadic
                                      (let γ0_0 :=
                                        M.SubPointer.get_struct_tuple_field (|
                                          γ,
                                          "core::option::Option::Some",
                                          0
                                        |) in
                                      M.read (|
                                        let~ _ : Ty.tuple [] :=
                                          M.call_closure (|
                                            Ty.tuple [],
                                            M.get_associated_function (|
                                              Ty.apply
                                                (Ty.path "core::result::Result")
                                                []
                                                [ Ty.tuple []; Ty.path "std::io::error::Error" ],
                                              "expect",
                                              [],
                                              []
                                            |),
                                            [
                                              M.value_with_ty
                                                (M.call_closure (|
                                                  Ty.apply
                                                    (Ty.path "core::result::Result")
                                                    []
                                                    [ Ty.tuple []; Ty.path "std::io::error::Error"
                                                    ],
                                                  M.get_trait_method (|
                                                    "std::io::Write",
                                                    Ty.path "std::fs::File",
                                                    [],
                                                    [],
                                                    "write_all",
                                                    [],
                                                    []
                                                  |),
                                                  [
                                                    M.value_with_ty
                                                      (M.borrow (| Pointer.Kind.MutRef, file |))
                                                      (Ty.apply
                                                        (Ty.path "&mut")
                                                        []
                                                        [ Ty.path "std::fs::File" ]);
                                                    M.value_with_ty
                                                      (M.borrow (|
                                                        Pointer.Kind.Ref,
                                                        M.deref (|
                                                          M.call_closure (|
                                                            Ty.apply
                                                              (Ty.path "&")
                                                              []
                                                              [
                                                                Ty.apply
                                                                  (Ty.path "slice")
                                                                  []
                                                                  [ Ty.path "u8" ]
                                                              ],
                                                            M.get_associated_function (|
                                                              Ty.path "str",
                                                              "as_bytes",
                                                              [],
                                                              []
                                                            |),
                                                            [
                                                              M.value_with_ty
                                                                (M.borrow (|
                                                                  Pointer.Kind.Ref,
                                                                  M.deref (|
                                                                    mk_str (| "Corro
" |)
                                                                  |)
                                                                |))
                                                                (Ty.apply
                                                                  (Ty.path "&")
                                                                  []
                                                                  [ Ty.path "str" ])
                                                            ]
                                                          |)
                                                        |)
                                                      |))
                                                      (Ty.apply
                                                        (Ty.path "&")
                                                        []
                                                        [
                                                          Ty.apply
                                                            (Ty.path "slice")
                                                            []
                                                            [ Ty.path "u8" ]
                                                        ])
                                                  ]
                                                |))
                                                (Ty.apply
                                                  (Ty.path "core::result::Result")
                                                  []
                                                  [ Ty.tuple []; Ty.path "std::io::error::Error" ]);
                                              M.value_with_ty
                                                (M.borrow (|
                                                  Pointer.Kind.Ref,
                                                  M.deref (|
                                                    mk_str (| "Could not write to ferris.txt" |)
                                                  |)
                                                |))
                                                (Ty.apply (Ty.path "&") [] [ Ty.path "str" ])
                                            ]
                                          |) in
                                        M.alloc (| Ty.tuple [], Value.Tuple [] |)
                                      |)))
                                ]
                              |) in
                            M.alloc (| Ty.tuple [], Value.Tuple [] |)))
                        |)
                      |)))
                ]
              |)
            |))
        |)))
    | _, _, _ => M.impossible "wrong number of arguments"
    end.
  
  Global Instance Instance_IsFunction_test_file_also :
    M.IsFunction.C "concurrent_tests::tests::test_file_also'1" test_file_also.
  Admitted.
  Global Typeclasses Opaque test_file_also.
End tests.
