(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module pin.
  Module unsafe_pinned.
    (* StructRecord
      {
        name := "UnsafePinned";
        const_params := [];
        ty_params := [ "T" ];
        fields := [ ("value", Ty.apply (Ty.path "core::cell::UnsafeCell") [] [ T ]) ];
      } *)
    
    Module Impl_core_marker_Sync_where_core_marker_Sized_T_where_core_marker_Sync_T_for_core_pin_unsafe_pinned_UnsafePinned_T.
      Definition Self (T : Ty.t) : Ty.t :=
        Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ].
      
      Axiom Implements :
        forall (T : Ty.t),
        M.IsTraitInstance
          "core::marker::Sync"
          (* Trait polymorphic consts *) []
          (* Trait polymorphic types *) []
          (Self T)
          (* Instance *) [].
    End Impl_core_marker_Sync_where_core_marker_Sized_T_where_core_marker_Sync_T_for_core_pin_unsafe_pinned_UnsafePinned_T.
    
    Module Impl_core_marker_Unpin_where_core_marker_Sized_T_for_core_pin_unsafe_pinned_UnsafePinned_T.
      Definition Self (T : Ty.t) : Ty.t :=
        Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ].
      
      Axiom Implements :
        forall (T : Ty.t),
        M.IsTraitInstance
          "core::marker::Unpin"
          (* Trait polymorphic consts *) []
          (* Trait polymorphic types *) []
          (Self T)
          (* Instance *) [].
    End Impl_core_marker_Unpin_where_core_marker_Sized_T_for_core_pin_unsafe_pinned_UnsafePinned_T.
    
    Module Impl_core_pin_unsafe_pinned_UnsafePinned_T.
      Definition Self (T : Ty.t) : Ty.t :=
        Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ].
      
      (*
          pub const fn new(value: T) -> Self {
              UnsafePinned { value: UnsafeCell::new(value) }
          }
      *)
      Definition new (T : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self T in
        match ε, τ, α with
        | [], [], [ value ] =>
          ltac:(M.monadic
            (let value := M.alloc (| T, value |) in
            Value.mkStructRecord
              "core::pin::unsafe_pinned::UnsafePinned"
              []
              [ T ]
              [
                ("value",
                  M.call_closure (|
                    Ty.apply (Ty.path "core::cell::UnsafeCell") [] [ T ],
                    M.get_associated_function (|
                      Ty.apply (Ty.path "core::cell::UnsafeCell") [] [ T ],
                      "new",
                      [],
                      []
                    |),
                    [ M.read (| value |) ]
                  |))
              ]))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Global Instance AssociatedFunction_new :
        forall (T : Ty.t),
        M.IsAssociatedFunction.C (Self T) "new" (new T).
      Admitted.
      Global Typeclasses Opaque new.
      
      (*
          pub const fn into_inner(self) -> T {
              self.value.into_inner()
          }
      *)
      Definition into_inner (T : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self T in
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ],
                self
              |) in
            M.call_closure (|
              T,
              M.get_associated_function (|
                Ty.apply (Ty.path "core::cell::UnsafeCell") [] [ T ],
                "into_inner",
                [],
                []
              |),
              [
                M.read (|
                  M.SubPointer.get_struct_record_field (|
                    self,
                    "core::pin::unsafe_pinned::UnsafePinned",
                    "value"
                  |)
                |)
              ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Global Instance AssociatedFunction_into_inner :
        forall (T : Ty.t),
        M.IsAssociatedFunction.C (Self T) "into_inner" (into_inner T).
      Admitted.
      Global Typeclasses Opaque into_inner.
      (*
          pub const fn get_mut_pinned(self: Pin<&mut Self>) -> *mut T {
              // SAFETY: we're not using `get_unchecked_mut` to unpin anything
              unsafe { self.get_unchecked_mut() }.get_mut_unchecked()
          }
      *)
      Definition get_mut_pinned
          (T : Ty.t)
          (ε : list Value.t)
          (τ : list Ty.t)
          (α : list Value.t)
          : M :=
        let Self : Ty.t := Self T in
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "core::pin::Pin")
                  []
                  [
                    Ty.apply
                      (Ty.path "&mut")
                      []
                      [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ] ]
                  ],
                self
              |) in
            M.call_closure (|
              Ty.apply (Ty.path "*mut") [] [ T ],
              M.get_associated_function (|
                Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ],
                "get_mut_unchecked",
                [],
                []
              |),
              [
                M.borrow (|
                  Pointer.Kind.MutRef,
                  M.deref (|
                    M.call_closure (|
                      Ty.apply
                        (Ty.path "&mut")
                        []
                        [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ] ],
                      M.get_associated_function (|
                        Ty.apply
                          (Ty.path "core::pin::Pin")
                          []
                          [
                            Ty.apply
                              (Ty.path "&mut")
                              []
                              [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ]
                              ]
                          ],
                        "get_unchecked_mut",
                        [],
                        []
                      |),
                      [ M.read (| self |) ]
                    |)
                  |)
                |)
              ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Global Instance AssociatedFunction_get_mut_pinned :
        forall (T : Ty.t),
        M.IsAssociatedFunction.C (Self T) "get_mut_pinned" (get_mut_pinned T).
      Admitted.
      Global Typeclasses Opaque get_mut_pinned.
      
      (*
          pub const fn get_mut_unchecked(&mut self) -> *mut T {
              ptr::from_mut(self) as *mut T
          }
      *)
      Definition get_mut_unchecked
          (T : Ty.t)
          (ε : list Value.t)
          (τ : list Ty.t)
          (α : list Value.t)
          : M :=
        let Self : Ty.t := Self T in
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "&mut")
                  []
                  [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ] ],
                self
              |) in
            M.cast
              (Ty.apply (Ty.path "*mut") [] [ T ])
              (M.call_closure (|
                Ty.apply
                  (Ty.path "*mut")
                  []
                  [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ] ],
                M.get_function (|
                  "core::ptr::from_mut",
                  [],
                  [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ] ]
                |),
                [ M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |) ]
              |))))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Global Instance AssociatedFunction_get_mut_unchecked :
        forall (T : Ty.t),
        M.IsAssociatedFunction.C (Self T) "get_mut_unchecked" (get_mut_unchecked T).
      Admitted.
      Global Typeclasses Opaque get_mut_unchecked.
      
      (*
          pub const fn get(&self) -> *mut T {
              self.value.get()
          }
      *)
      Definition get (T : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self T in
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "&")
                  []
                  [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ] ],
                self
              |) in
            M.call_closure (|
              Ty.apply (Ty.path "*mut") [] [ T ],
              M.get_associated_function (|
                Ty.apply (Ty.path "core::cell::UnsafeCell") [] [ T ],
                "get",
                [],
                []
              |),
              [
                M.borrow (|
                  Pointer.Kind.Ref,
                  M.SubPointer.get_struct_record_field (|
                    M.deref (| M.read (| self |) |),
                    "core::pin::unsafe_pinned::UnsafePinned",
                    "value"
                  |)
                |)
              ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Global Instance AssociatedFunction_get :
        forall (T : Ty.t),
        M.IsAssociatedFunction.C (Self T) "get" (get T).
      Admitted.
      Global Typeclasses Opaque get.
      
      (*
          pub const fn raw_get(this: *const Self) -> *mut T {
              this as *const T as *mut T
          }
      *)
      Definition raw_get (T : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self T in
        match ε, τ, α with
        | [], [], [ this ] =>
          ltac:(M.monadic
            (let this :=
              M.alloc (|
                Ty.apply
                  (Ty.path "*const")
                  []
                  [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ] ],
                this
              |) in
            M.cast
              (Ty.apply (Ty.path "*mut") [] [ T ])
              (M.cast (Ty.apply (Ty.path "*const") [] [ T ]) (M.read (| this |)))))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Global Instance AssociatedFunction_raw_get :
        forall (T : Ty.t),
        M.IsAssociatedFunction.C (Self T) "raw_get" (raw_get T).
      Admitted.
      Global Typeclasses Opaque raw_get.
      
      (*
          pub const fn raw_get_mut(this: *mut Self) -> *mut T {
              this as *mut T
          }
      *)
      Definition raw_get_mut (T : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self T in
        match ε, τ, α with
        | [], [], [ this ] =>
          ltac:(M.monadic
            (let this :=
              M.alloc (|
                Ty.apply
                  (Ty.path "*mut")
                  []
                  [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ] ],
                this
              |) in
            M.cast (Ty.apply (Ty.path "*mut") [] [ T ]) (M.read (| this |))))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Global Instance AssociatedFunction_raw_get_mut :
        forall (T : Ty.t),
        M.IsAssociatedFunction.C (Self T) "raw_get_mut" (raw_get_mut T).
      Admitted.
      Global Typeclasses Opaque raw_get_mut.
    End Impl_core_pin_unsafe_pinned_UnsafePinned_T.
    
    
    Module Impl_core_default_Default_where_core_default_Default_T_for_core_pin_unsafe_pinned_UnsafePinned_T.
      Definition Self (T : Ty.t) : Ty.t :=
        Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ].
      
      (*
          fn default() -> Self {
              UnsafePinned::new(T::default())
          }
      *)
      Definition default (T : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self T in
        match ε, τ, α with
        | [], [], [] =>
          ltac:(M.monadic
            (M.call_closure (|
              Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ],
              M.get_associated_function (|
                Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ],
                "new",
                [],
                []
              |),
              [
                M.call_closure (|
                  T,
                  M.get_trait_method (| "core::default::Default", T, [], [], "default", [], [] |),
                  []
                |)
              ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Axiom Implements :
        forall (T : Ty.t),
        M.IsTraitInstance
          "core::default::Default"
          (* Trait polymorphic consts *) []
          (* Trait polymorphic types *) []
          (Self T)
          (* Instance *) [ ("default", InstanceField.Method (default T)) ].
    End Impl_core_default_Default_where_core_default_Default_T_for_core_pin_unsafe_pinned_UnsafePinned_T.
    
    Module Impl_core_convert_From_T_for_core_pin_unsafe_pinned_UnsafePinned_T.
      Definition Self (T : Ty.t) : Ty.t :=
        Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ].
      
      (*
          fn from(value: T) -> Self {
              UnsafePinned::new(value)
          }
      *)
      Definition from (T : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self T in
        match ε, τ, α with
        | [], [], [ value ] =>
          ltac:(M.monadic
            (let value := M.alloc (| T, value |) in
            M.call_closure (|
              Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ],
              M.get_associated_function (|
                Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ],
                "new",
                [],
                []
              |),
              [ M.read (| value |) ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Axiom Implements :
        forall (T : Ty.t),
        M.IsTraitInstance
          "core::convert::From"
          (* Trait polymorphic consts *) []
          (* Trait polymorphic types *) [ T ]
          (Self T)
          (* Instance *) [ ("from", InstanceField.Method (from T)) ].
    End Impl_core_convert_From_T_for_core_pin_unsafe_pinned_UnsafePinned_T.
    
    Module Impl_core_fmt_Debug_where_core_marker_Sized_T_for_core_pin_unsafe_pinned_UnsafePinned_T.
      Definition Self (T : Ty.t) : Ty.t :=
        Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ].
      
      (*
          fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
              f.debug_struct("UnsafePinned").finish_non_exhaustive()
          }
      *)
      Definition fmt (T : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self T in
        match ε, τ, α with
        | [], [], [ self; f ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "&")
                  []
                  [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ] ],
                self
              |) in
            let f :=
              M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
            M.call_closure (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [ Ty.tuple []; Ty.path "core::fmt::Error" ],
              M.get_associated_function (|
                Ty.path "core::fmt::builders::DebugStruct",
                "finish_non_exhaustive",
                [],
                []
              |),
              [
                M.borrow (|
                  Pointer.Kind.MutRef,
                  M.alloc (|
                    Ty.path "core::fmt::builders::DebugStruct",
                    M.call_closure (|
                      Ty.path "core::fmt::builders::DebugStruct",
                      M.get_associated_function (|
                        Ty.path "core::fmt::Formatter",
                        "debug_struct",
                        [],
                        []
                      |),
                      [
                        M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                        M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "UnsafePinned" |) |) |)
                      ]
                    |)
                  |)
                |)
              ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Axiom Implements :
        forall (T : Ty.t),
        M.IsTraitInstance
          "core::fmt::Debug"
          (* Trait polymorphic consts *) []
          (* Trait polymorphic types *) []
          (Self T)
          (* Instance *) [ ("fmt", InstanceField.Method (fmt T)) ].
    End Impl_core_fmt_Debug_where_core_marker_Sized_T_for_core_pin_unsafe_pinned_UnsafePinned_T.
    
    Module Impl_core_ops_unsize_CoerceUnsized_where_core_ops_unsize_CoerceUnsized_T_U_core_pin_unsafe_pinned_UnsafePinned_U_for_core_pin_unsafe_pinned_UnsafePinned_T.
      Definition Self (T U : Ty.t) : Ty.t :=
        Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ].
      
      Axiom Implements :
        forall (T U : Ty.t),
        M.IsTraitInstance
          "core::ops::unsize::CoerceUnsized"
          (* Trait polymorphic consts *) []
          (* Trait polymorphic types *)
          [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ U ] ]
          (Self T U)
          (* Instance *) [].
    End Impl_core_ops_unsize_CoerceUnsized_where_core_ops_unsize_CoerceUnsized_T_U_core_pin_unsafe_pinned_UnsafePinned_U_for_core_pin_unsafe_pinned_UnsafePinned_T.
    
    Module Impl_core_ops_unsize_DispatchFromDyn_where_core_ops_unsize_DispatchFromDyn_T_U_core_pin_unsafe_pinned_UnsafePinned_U_for_core_pin_unsafe_pinned_UnsafePinned_T.
      Definition Self (T U : Ty.t) : Ty.t :=
        Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ T ].
      
      Axiom Implements :
        forall (T U : Ty.t),
        M.IsTraitInstance
          "core::ops::unsize::DispatchFromDyn"
          (* Trait polymorphic consts *) []
          (* Trait polymorphic types *)
          [ Ty.apply (Ty.path "core::pin::unsafe_pinned::UnsafePinned") [] [ U ] ]
          (Self T U)
          (* Instance *) [].
    End Impl_core_ops_unsize_DispatchFromDyn_where_core_ops_unsize_DispatchFromDyn_T_U_core_pin_unsafe_pinned_UnsafePinned_U_for_core_pin_unsafe_pinned_UnsafePinned_T.
  End unsafe_pinned.
End pin.
