(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Parameter main : (list Value.t) -> (list Ty.t) -> (list Value.t) -> M.

Global Instance Instance_IsFunction_main : M.IsFunction.C "macro_example::main" main.
Admitted.
