(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module constants.
  Definition value_BLOCK_HASH_HISTORY (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u64", Value.Integer IntegerKind.U64 256 |))).
  
  Global Instance Instance_IsConstant_value_BLOCK_HASH_HISTORY :
    M.IsFunction.C "revm_primitives::constants::BLOCK_HASH_HISTORY" value_BLOCK_HASH_HISTORY.
  Admitted.
  Global Typeclasses Opaque value_BLOCK_HASH_HISTORY.
  
  Definition value_PRECOMPILE3 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic
      (M.alloc (|
        Ty.path "alloy_primitives::bits::address::Address",
        M.call_closure (|
          Ty.path "alloy_primitives::bits::address::Address",
          M.get_associated_function (|
            Ty.path "alloy_primitives::bits::address::Address",
            "new",
            [],
            []
          |),
          [
            Value.Array
              [
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 0;
                Value.Integer IntegerKind.U8 3
              ]
          ]
        |)
      |))).
  
  Global Instance Instance_IsConstant_value_PRECOMPILE3 :
    M.IsFunction.C "revm_primitives::constants::PRECOMPILE3" value_PRECOMPILE3.
  Admitted.
  Global Typeclasses Opaque value_PRECOMPILE3.
  
  Definition value_STACK_LIMIT (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "usize", Value.Integer IntegerKind.Usize 1024 |))).
  
  Global Instance Instance_IsConstant_value_STACK_LIMIT :
    M.IsFunction.C "revm_primitives::constants::STACK_LIMIT" value_STACK_LIMIT.
  Admitted.
  Global Typeclasses Opaque value_STACK_LIMIT.
  
  Definition value_CALL_STACK_LIMIT (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic (M.alloc (| Ty.path "u64", Value.Integer IntegerKind.U64 1024 |))).
  
  Global Instance Instance_IsConstant_value_CALL_STACK_LIMIT :
    M.IsFunction.C "revm_primitives::constants::CALL_STACK_LIMIT" value_CALL_STACK_LIMIT.
  Admitted.
  Global Typeclasses Opaque value_CALL_STACK_LIMIT.
  
  Definition value_KECCAK_EMPTY (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    ltac:(M.monadic
      (M.alloc (|
        Ty.apply
          (Ty.path "alloy_primitives::bits::fixed::FixedBytes")
          [ Value.Integer IntegerKind.Usize 32 ]
          [],
        M.call_closure (|
          Ty.apply
            (Ty.path "alloy_primitives::bits::fixed::FixedBytes")
            [ Value.Integer IntegerKind.Usize 32 ]
            [],
          M.get_associated_function (|
            Ty.apply
              (Ty.path "alloy_primitives::bits::fixed::FixedBytes")
              [ Value.Integer IntegerKind.Usize 32 ]
              [],
            "new",
            [],
            []
          |),
          [
            M.read (|
              get_constant (|
                "revm_primitives::constants::KECCAK_EMPTY_discriminant",
                Ty.apply (Ty.path "array") [ Value.Integer IntegerKind.Usize 32 ] [ Ty.path "u8" ]
              |)
            |)
          ]
        |)
      |))).
  
  Global Instance Instance_IsConstant_value_KECCAK_EMPTY :
    M.IsFunction.C "revm_primitives::constants::KECCAK_EMPTY" value_KECCAK_EMPTY.
  Admitted.
  Global Typeclasses Opaque value_KECCAK_EMPTY.
End constants.
