(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module transaction.
  Module alloy_types.
    Module Impl_revm_context_interface_transaction_eip2930_AccessListItemTr_for_alloy_eip2930_AccessListItem.
      Definition Self : Ty.t := Ty.path "alloy_eip2930::AccessListItem".
      
      (*
          fn address(&self) -> &Address {
              &self.address
          }
      *)
      Definition address (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply (Ty.path "&") [] [ Ty.path "alloy_eip2930::AccessListItem" ],
                self
              |) in
            M.borrow (|
              Pointer.Kind.Ref,
              M.deref (|
                M.borrow (|
                  Pointer.Kind.Ref,
                  M.SubPointer.get_struct_record_field (|
                    M.deref (| M.read (| self |) |),
                    "alloy_eip2930::AccessListItem",
                    "address"
                  |)
                |)
              |)
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      (*
          fn storage_slots(&self) -> impl Iterator<Item = &B256> {
              self.storage_keys.iter()
          }
      *)
      Definition storage_slots (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply (Ty.path "&") [] [ Ty.path "alloy_eip2930::AccessListItem" ],
                self
              |) in
            M.call_closure (|
              Ty.apply
                (Ty.path "core::slice::iter::Iter")
                []
                [
                  Ty.apply
                    (Ty.path "alloy_primitives::bits::fixed::FixedBytes")
                    [ Value.Integer IntegerKind.Usize 32 ]
                    []
                ],
              M.get_associated_function (|
                Ty.apply
                  (Ty.path "slice")
                  []
                  [
                    Ty.apply
                      (Ty.path "alloy_primitives::bits::fixed::FixedBytes")
                      [ Value.Integer IntegerKind.Usize 32 ]
                      []
                  ],
                "iter",
                [],
                []
              |),
              [
                M.borrow (|
                  Pointer.Kind.Ref,
                  M.deref (|
                    M.call_closure (|
                      Ty.apply
                        (Ty.path "&")
                        []
                        [
                          Ty.apply
                            (Ty.path "slice")
                            []
                            [
                              Ty.apply
                                (Ty.path "alloy_primitives::bits::fixed::FixedBytes")
                                [ Value.Integer IntegerKind.Usize 32 ]
                                []
                            ]
                        ],
                      M.get_trait_method (|
                        "core::ops::deref::Deref",
                        Ty.apply
                          (Ty.path "alloc::vec::Vec")
                          []
                          [
                            Ty.apply
                              (Ty.path "alloy_primitives::bits::fixed::FixedBytes")
                              [ Value.Integer IntegerKind.Usize 32 ]
                              [];
                            Ty.path "alloc::alloc::Global"
                          ],
                        [],
                        [],
                        "deref",
                        [],
                        []
                      |),
                      [
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "alloy_eip2930::AccessListItem",
                            "storage_keys"
                          |)
                        |)
                      ]
                    |)
                  |)
                |)
              ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Axiom Implements :
        M.IsTraitInstance
          "revm_context_interface::transaction::eip2930::AccessListItemTr"
          (* Trait polymorphic consts *) []
          (* Trait polymorphic types *) []
          Self
          (* Instance *)
          [
            ("address", InstanceField.Method address);
            ("storage_slots", InstanceField.Method storage_slots)
          ].
    End Impl_revm_context_interface_transaction_eip2930_AccessListItemTr_for_alloy_eip2930_AccessListItem.
    
    Module Impl_revm_context_interface_transaction_eip7702_AuthorizationTr_for_alloy_eip7702_auth_list_SignedAuthorization.
      Definition Self : Ty.t := Ty.path "alloy_eip7702::auth_list::SignedAuthorization".
      
      (*
          fn authority(&self) -> Option<Address> {
              self.recover_authority().ok()
          }
      *)
      Definition authority (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "&")
                  []
                  [ Ty.path "alloy_eip7702::auth_list::SignedAuthorization" ],
                self
              |) in
            M.call_closure (|
              Ty.apply
                (Ty.path "core::option::Option")
                []
                [ Ty.path "alloy_primitives::bits::address::Address" ],
              M.get_associated_function (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.path "alloy_primitives::bits::address::Address";
                    Ty.path "alloy_eip7702::error::Eip7702Error"
                  ],
                "ok",
                [],
                []
              |),
              [
                M.call_closure (|
                  Ty.apply
                    (Ty.path "core::result::Result")
                    []
                    [
                      Ty.path "alloy_primitives::bits::address::Address";
                      Ty.path "alloy_eip7702::error::Eip7702Error"
                    ],
                  M.get_associated_function (|
                    Ty.path "alloy_eip7702::auth_list::SignedAuthorization",
                    "recover_authority",
                    [],
                    []
                  |),
                  [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
                |)
              ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      (*
          fn chain_id(&self) -> U256 {
              self.chain_id
          }
      *)
      Definition chain_id (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "&")
                  []
                  [ Ty.path "alloy_eip7702::auth_list::SignedAuthorization" ],
                self
              |) in
            M.read (|
              M.SubPointer.get_struct_record_field (|
                M.deref (|
                  M.call_closure (|
                    Ty.apply (Ty.path "&") [] [ Ty.path "alloy_eip7702::auth_list::Authorization" ],
                    M.get_trait_method (|
                      "core::ops::deref::Deref",
                      Ty.path "alloy_eip7702::auth_list::SignedAuthorization",
                      [],
                      [],
                      "deref",
                      [],
                      []
                    |),
                    [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
                  |)
                |),
                "alloy_eip7702::auth_list::Authorization",
                "chain_id"
              |)
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      (*
          fn nonce(&self) -> u64 {
              self.nonce
          }
      *)
      Definition nonce (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "&")
                  []
                  [ Ty.path "alloy_eip7702::auth_list::SignedAuthorization" ],
                self
              |) in
            M.read (|
              M.SubPointer.get_struct_record_field (|
                M.deref (|
                  M.call_closure (|
                    Ty.apply (Ty.path "&") [] [ Ty.path "alloy_eip7702::auth_list::Authorization" ],
                    M.get_trait_method (|
                      "core::ops::deref::Deref",
                      Ty.path "alloy_eip7702::auth_list::SignedAuthorization",
                      [],
                      [],
                      "deref",
                      [],
                      []
                    |),
                    [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
                  |)
                |),
                "alloy_eip7702::auth_list::Authorization",
                "nonce"
              |)
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      (*
          fn address(&self) -> Address {
              self.address
          }
      *)
      Definition address (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "&")
                  []
                  [ Ty.path "alloy_eip7702::auth_list::SignedAuthorization" ],
                self
              |) in
            M.read (|
              M.SubPointer.get_struct_record_field (|
                M.deref (|
                  M.call_closure (|
                    Ty.apply (Ty.path "&") [] [ Ty.path "alloy_eip7702::auth_list::Authorization" ],
                    M.get_trait_method (|
                      "core::ops::deref::Deref",
                      Ty.path "alloy_eip7702::auth_list::SignedAuthorization",
                      [],
                      [],
                      "deref",
                      [],
                      []
                    |),
                    [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
                  |)
                |),
                "alloy_eip7702::auth_list::Authorization",
                "address"
              |)
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Axiom Implements :
        M.IsTraitInstance
          "revm_context_interface::transaction::eip7702::AuthorizationTr"
          (* Trait polymorphic consts *) []
          (* Trait polymorphic types *) []
          Self
          (* Instance *)
          [
            ("authority", InstanceField.Method authority);
            ("chain_id", InstanceField.Method chain_id);
            ("nonce", InstanceField.Method nonce);
            ("address", InstanceField.Method address)
          ].
    End Impl_revm_context_interface_transaction_eip7702_AuthorizationTr_for_alloy_eip7702_auth_list_SignedAuthorization.
    
    Module Impl_revm_context_interface_transaction_eip7702_AuthorizationTr_for_alloy_eip7702_auth_list_RecoveredAuthorization.
      Definition Self : Ty.t := Ty.path "alloy_eip7702::auth_list::RecoveredAuthorization".
      
      (*
          fn authority(&self) -> Option<Address> {
              self.authority()
          }
      *)
      Definition authority (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "&")
                  []
                  [ Ty.path "alloy_eip7702::auth_list::RecoveredAuthorization" ],
                self
              |) in
            M.call_closure (|
              Ty.apply
                (Ty.path "core::option::Option")
                []
                [ Ty.path "alloy_primitives::bits::address::Address" ],
              M.get_associated_function (|
                Ty.path "alloy_eip7702::auth_list::RecoveredAuthorization",
                "authority",
                [],
                []
              |),
              [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      (*
          fn chain_id(&self) -> U256 {
              self.chain_id
          }
      *)
      Definition chain_id (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "&")
                  []
                  [ Ty.path "alloy_eip7702::auth_list::RecoveredAuthorization" ],
                self
              |) in
            M.read (|
              M.SubPointer.get_struct_record_field (|
                M.deref (|
                  M.call_closure (|
                    Ty.apply (Ty.path "&") [] [ Ty.path "alloy_eip7702::auth_list::Authorization" ],
                    M.get_trait_method (|
                      "core::ops::deref::Deref",
                      Ty.path "alloy_eip7702::auth_list::RecoveredAuthorization",
                      [],
                      [],
                      "deref",
                      [],
                      []
                    |),
                    [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
                  |)
                |),
                "alloy_eip7702::auth_list::Authorization",
                "chain_id"
              |)
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      (*
          fn nonce(&self) -> u64 {
              self.nonce
          }
      *)
      Definition nonce (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "&")
                  []
                  [ Ty.path "alloy_eip7702::auth_list::RecoveredAuthorization" ],
                self
              |) in
            M.read (|
              M.SubPointer.get_struct_record_field (|
                M.deref (|
                  M.call_closure (|
                    Ty.apply (Ty.path "&") [] [ Ty.path "alloy_eip7702::auth_list::Authorization" ],
                    M.get_trait_method (|
                      "core::ops::deref::Deref",
                      Ty.path "alloy_eip7702::auth_list::RecoveredAuthorization",
                      [],
                      [],
                      "deref",
                      [],
                      []
                    |),
                    [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
                  |)
                |),
                "alloy_eip7702::auth_list::Authorization",
                "nonce"
              |)
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      (*
          fn address(&self) -> Address {
              self.address
          }
      *)
      Definition address (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply
                  (Ty.path "&")
                  []
                  [ Ty.path "alloy_eip7702::auth_list::RecoveredAuthorization" ],
                self
              |) in
            M.read (|
              M.SubPointer.get_struct_record_field (|
                M.deref (|
                  M.call_closure (|
                    Ty.apply (Ty.path "&") [] [ Ty.path "alloy_eip7702::auth_list::Authorization" ],
                    M.get_trait_method (|
                      "core::ops::deref::Deref",
                      Ty.path "alloy_eip7702::auth_list::RecoveredAuthorization",
                      [],
                      [],
                      "deref",
                      [],
                      []
                    |),
                    [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
                  |)
                |),
                "alloy_eip7702::auth_list::Authorization",
                "address"
              |)
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Axiom Implements :
        M.IsTraitInstance
          "revm_context_interface::transaction::eip7702::AuthorizationTr"
          (* Trait polymorphic consts *) []
          (* Trait polymorphic types *) []
          Self
          (* Instance *)
          [
            ("authority", InstanceField.Method authority);
            ("chain_id", InstanceField.Method chain_id);
            ("nonce", InstanceField.Method nonce);
            ("address", InstanceField.Method address)
          ].
    End Impl_revm_context_interface_transaction_eip7702_AuthorizationTr_for_alloy_eip7702_auth_list_RecoveredAuthorization.
    
    Module Impl_revm_context_interface_transaction_eip7702_AuthorizationTr_where_revm_context_interface_transaction_eip7702_AuthorizationTr_L_where_revm_context_interface_transaction_eip7702_AuthorizationTr_R_for_either_Either_L_R.
      Definition Self (L R : Ty.t) : Ty.t := Ty.apply (Ty.path "either::Either") [] [ L; R ].
      
      (*
          fn authority(&self) -> Option<Address> {
              for_both!(self, s => s.authority())
          }
      *)
      Definition authority (L R : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self L R in
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "either::Either") [] [ L; R ] ],
                self
              |) in
            M.match_operator (|
              Ty.apply
                (Ty.path "core::option::Option")
                []
                [ Ty.path "alloy_primitives::bits::address::Address" ],
              self,
              [
                fun γ =>
                  ltac:(M.monadic
                    (let γ := M.deref (| M.read (| γ |) |) in
                    let γ1_0 :=
                      M.SubPointer.get_struct_tuple_field (| γ, "either::Either::Left", 0 |) in
                    let _ := M.read (| γ1_0 |) in
                    let s :=
                      M.alloc (|
                        Ty.apply (Ty.path "&") [] [ L ],
                        M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                      |) in
                    M.call_closure (|
                      Ty.apply
                        (Ty.path "core::option::Option")
                        []
                        [ Ty.path "alloy_primitives::bits::address::Address" ],
                      M.get_trait_method (|
                        "revm_context_interface::transaction::eip7702::AuthorizationTr",
                        L,
                        [],
                        [],
                        "authority",
                        [],
                        []
                      |),
                      [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| s |) |) |) ]
                    |)));
                fun γ =>
                  ltac:(M.monadic
                    (let γ := M.deref (| M.read (| γ |) |) in
                    let γ1_0 :=
                      M.SubPointer.get_struct_tuple_field (| γ, "either::Either::Right", 0 |) in
                    let _ := M.read (| γ1_0 |) in
                    let s :=
                      M.alloc (|
                        Ty.apply (Ty.path "&") [] [ R ],
                        M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                      |) in
                    M.call_closure (|
                      Ty.apply
                        (Ty.path "core::option::Option")
                        []
                        [ Ty.path "alloy_primitives::bits::address::Address" ],
                      M.get_trait_method (|
                        "revm_context_interface::transaction::eip7702::AuthorizationTr",
                        R,
                        [],
                        [],
                        "authority",
                        [],
                        []
                      |),
                      [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| s |) |) |) ]
                    |)))
              ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      (*
          fn chain_id(&self) -> U256 {
              for_both!(self, s => s.chain_id())
          }
      *)
      Definition chain_id (L R : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self L R in
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "either::Either") [] [ L; R ] ],
                self
              |) in
            M.match_operator (|
              Ty.apply
                (Ty.path "ruint::Uint")
                [ Value.Integer IntegerKind.Usize 256; Value.Integer IntegerKind.Usize 4 ]
                [],
              self,
              [
                fun γ =>
                  ltac:(M.monadic
                    (let γ := M.deref (| M.read (| γ |) |) in
                    let γ1_0 :=
                      M.SubPointer.get_struct_tuple_field (| γ, "either::Either::Left", 0 |) in
                    let _ := M.read (| γ1_0 |) in
                    let s :=
                      M.alloc (|
                        Ty.apply (Ty.path "&") [] [ L ],
                        M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                      |) in
                    M.call_closure (|
                      Ty.apply
                        (Ty.path "ruint::Uint")
                        [ Value.Integer IntegerKind.Usize 256; Value.Integer IntegerKind.Usize 4 ]
                        [],
                      M.get_trait_method (|
                        "revm_context_interface::transaction::eip7702::AuthorizationTr",
                        L,
                        [],
                        [],
                        "chain_id",
                        [],
                        []
                      |),
                      [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| s |) |) |) ]
                    |)));
                fun γ =>
                  ltac:(M.monadic
                    (let γ := M.deref (| M.read (| γ |) |) in
                    let γ1_0 :=
                      M.SubPointer.get_struct_tuple_field (| γ, "either::Either::Right", 0 |) in
                    let _ := M.read (| γ1_0 |) in
                    let s :=
                      M.alloc (|
                        Ty.apply (Ty.path "&") [] [ R ],
                        M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                      |) in
                    M.call_closure (|
                      Ty.apply
                        (Ty.path "ruint::Uint")
                        [ Value.Integer IntegerKind.Usize 256; Value.Integer IntegerKind.Usize 4 ]
                        [],
                      M.get_trait_method (|
                        "revm_context_interface::transaction::eip7702::AuthorizationTr",
                        R,
                        [],
                        [],
                        "chain_id",
                        [],
                        []
                      |),
                      [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| s |) |) |) ]
                    |)))
              ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      (*
          fn nonce(&self) -> u64 {
              for_both!(self, s => s.nonce())
          }
      *)
      Definition nonce (L R : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self L R in
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "either::Either") [] [ L; R ] ],
                self
              |) in
            M.match_operator (|
              Ty.path "u64",
              self,
              [
                fun γ =>
                  ltac:(M.monadic
                    (let γ := M.deref (| M.read (| γ |) |) in
                    let γ1_0 :=
                      M.SubPointer.get_struct_tuple_field (| γ, "either::Either::Left", 0 |) in
                    let _ := M.read (| γ1_0 |) in
                    let s :=
                      M.alloc (|
                        Ty.apply (Ty.path "&") [] [ L ],
                        M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                      |) in
                    M.call_closure (|
                      Ty.path "u64",
                      M.get_trait_method (|
                        "revm_context_interface::transaction::eip7702::AuthorizationTr",
                        L,
                        [],
                        [],
                        "nonce",
                        [],
                        []
                      |),
                      [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| s |) |) |) ]
                    |)));
                fun γ =>
                  ltac:(M.monadic
                    (let γ := M.deref (| M.read (| γ |) |) in
                    let γ1_0 :=
                      M.SubPointer.get_struct_tuple_field (| γ, "either::Either::Right", 0 |) in
                    let _ := M.read (| γ1_0 |) in
                    let s :=
                      M.alloc (|
                        Ty.apply (Ty.path "&") [] [ R ],
                        M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                      |) in
                    M.call_closure (|
                      Ty.path "u64",
                      M.get_trait_method (|
                        "revm_context_interface::transaction::eip7702::AuthorizationTr",
                        R,
                        [],
                        [],
                        "nonce",
                        [],
                        []
                      |),
                      [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| s |) |) |) ]
                    |)))
              ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      (*
          fn address(&self) -> Address {
              for_both!(self, s => s.address())
          }
      *)
      Definition address (L R : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
        let Self : Ty.t := Self L R in
        match ε, τ, α with
        | [], [], [ self ] =>
          ltac:(M.monadic
            (let self :=
              M.alloc (|
                Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "either::Either") [] [ L; R ] ],
                self
              |) in
            M.match_operator (|
              Ty.path "alloy_primitives::bits::address::Address",
              self,
              [
                fun γ =>
                  ltac:(M.monadic
                    (let γ := M.deref (| M.read (| γ |) |) in
                    let γ1_0 :=
                      M.SubPointer.get_struct_tuple_field (| γ, "either::Either::Left", 0 |) in
                    let _ := M.read (| γ1_0 |) in
                    let s :=
                      M.alloc (|
                        Ty.apply (Ty.path "&") [] [ L ],
                        M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                      |) in
                    M.call_closure (|
                      Ty.path "alloy_primitives::bits::address::Address",
                      M.get_trait_method (|
                        "revm_context_interface::transaction::eip7702::AuthorizationTr",
                        L,
                        [],
                        [],
                        "address",
                        [],
                        []
                      |),
                      [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| s |) |) |) ]
                    |)));
                fun γ =>
                  ltac:(M.monadic
                    (let γ := M.deref (| M.read (| γ |) |) in
                    let γ1_0 :=
                      M.SubPointer.get_struct_tuple_field (| γ, "either::Either::Right", 0 |) in
                    let _ := M.read (| γ1_0 |) in
                    let s :=
                      M.alloc (|
                        Ty.apply (Ty.path "&") [] [ R ],
                        M.borrow (| Pointer.Kind.Ref, γ1_0 |)
                      |) in
                    M.call_closure (|
                      Ty.path "alloy_primitives::bits::address::Address",
                      M.get_trait_method (|
                        "revm_context_interface::transaction::eip7702::AuthorizationTr",
                        R,
                        [],
                        [],
                        "address",
                        [],
                        []
                      |),
                      [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| s |) |) |) ]
                    |)))
              ]
            |)))
        | _, _, _ => M.impossible "wrong number of arguments"
        end.
      
      Axiom Implements :
        forall (L R : Ty.t),
        M.IsTraitInstance
          "revm_context_interface::transaction::eip7702::AuthorizationTr"
          (* Trait polymorphic consts *) []
          (* Trait polymorphic types *) []
          (Self L R)
          (* Instance *)
          [
            ("authority", InstanceField.Method (authority L R));
            ("chain_id", InstanceField.Method (chain_id L R));
            ("nonce", InstanceField.Method (nonce L R));
            ("address", InstanceField.Method (address L R))
          ].
    End Impl_revm_context_interface_transaction_eip7702_AuthorizationTr_where_revm_context_interface_transaction_eip7702_AuthorizationTr_L_where_revm_context_interface_transaction_eip7702_AuthorizationTr_R_for_either_Either_L_R.
  End alloy_types.
End transaction.
