(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Parameter tuple_assignment : (list Value.t) -> (list Ty.t) -> (list Value.t) -> M.

Global Instance Instance_IsFunction_tuple_assignment :
  M.IsFunction.C "tuple_assignment::tuple_assignment" tuple_assignment.
Admitted.
