name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get disk space
      run: df -h
    - name: Download Git submodules
      run: git submodule update --init --recursive --depth 1
    - name: Get disk space
      run: df -h
    - uses: coq-community/docker-coq-action@v1
      with:
        custom_image: rocq/rocq-prover:9.0
        custom_script: |
          startGroup "Install dependencies"
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source "$HOME/.cargo/env"
            rustup toolchain install nightly-2024-12-07-x86_64-unknown-linux-gnu
            cargo --version
            sudo ln -s `which python3` /usr/bin/python
            opam install -y --deps-only RocqOfRust/rocq-of-rust.opam
          endGroup
          startGroup "Build"
            sudo chown -R $(whoami) .
            cargo clean
            rustup component add rust-src rustc-dev llvm-tools-preview
            cargo build --verbose
          endGroup
          startGroup "Install"
            cargo install --path lib/
          endGroup
          startGroup "Format check"
            cargo fmt --check
          endGroup
          startGroup "Lint"
            cargo clippy --all-targets --all-features -- -D warnings
          endGroup
          startGroup "Pre-process the smart contracts"
            cd contracts
            python source_to_generated.py
            cd generated
            for dir in * ; do cd $dir ; cargo check ; cd .. ; done
            cd ../..
          endGroup
          # We disable for now this translation as this makes a panic!
          # startGroup "Translate Ink! library"
          #   cd RocqOfRust
          #   ./generate_ink_example.sh
          #   cd ..
          # endGroup
          # Generate markdown with progress on links for instructions
          startGroup "Generate markdown with progress on links for instructions"
            cd RocqOfRust/revm/revm_interpreter/instructions/links
            python count_admitted.py > progress_on_links.md
            cd ../../../../..
          endGroup
          startGroup "Save space"
            cargo clean
          endGroup
          startGroup "Install Jinja2"
            sudo apt-get update && sudo apt-get install -y python3-jinja2
          endGroup
          startGroup "Regenerate all Rocq files"
            ./.github/workflows/regenerate_all.sh
          endGroup
          startGroup "Check that the diff is empty (excluding submodules)"
            git -c color.ui=always diff --exit-code --ignore-submodules=dirty
          endGroup
          startGroup "Save space again"
            cd third-party
            for dir in */ ; do
              cd "$dir"
              echo "Cleaning $dir"
              cargo clean
              cd ..
            done
            cd ..
          endGroup
          startGroup "Compile Rocq translations"
            cd RocqOfRust
            make -j3
            cd ..
          endGroup
